'use strict';
const $ = s => document.querySelector(s);
const cities=['دمشق','ريف دمشق','حلب','حمص','حماة','اللاذقية','طرطوس','إدلب','درعا','السويداء','القنيطرة','دير الزور','الرقة','الحسكة'];
const kinds=['شقة','منزل','فيلا','أرض','محل تجاري','مكتب','بناء','مزرعة'];
let me=null, mode='sale', mine=false, favoritesOnly=false, registration=false, pendingAdd=false, items=[], offset=0, total=0, requestId=0, deleteId=null;
let favorites=new Set();
try { const v=JSON.parse(localStorage.getItem('aq_favorites')||'[]'); if(Array.isArray(v)) favorites=new Set(v.filter(Number.isInteger)); } catch {}
function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').style.display='none',4000);}
const STATIC_MODE=location.hostname.endsWith('.github.io');
const demoProperties=[
{id:1,user_id:0,title:'فيلا للبيع - منطقة برزة',city:'دمشق',kind:'فيلا',mode:'sale',price:180000,area:500,rooms:4,description:'إعلان تجريبي لعرض شكل صفحة العقار.',phone:'+963000000001',advertiser:'معلن تجريبي'},
{id:2,user_id:0,title:'شقة للبيع - حي الزهراء',city:'حمص',kind:'شقة',mode:'sale',price:95000,area:150,rooms:3,description:'إعلان تجريبي لعرض البحث والتواصل.',phone:'+963000000002',advertiser:'معلن تجريبي'},
{id:3,user_id:0,title:'شقة للإيجار - المزة',city:'دمشق',kind:'شقة',mode:'rent',price:650,area:120,rooms:3,description:'إعلان تجريبي، والإيجار محسوب شهريًا.',phone:'+963000000003',advertiser:'معلن تجريبي'}];
function readStore(key,fallback){try{const value=JSON.parse(localStorage.getItem(key));return value===null?fallback:value;}catch{return fallback;}}
function writeStore(key,value){try{localStorage.setItem(key,JSON.stringify(value));}catch{throw Error('تعذر حفظ البيانات على هذا الجهاز.');}}
async function passwordDigest(password){if(!crypto.subtle)throw Error('المتصفح لا يدعم تسجيل الدخول الآمن محليًا.');const bytes=new TextEncoder().encode(password);const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(v=>v.toString(16).padStart(2,'0')).join('');}
async function localApi(path,method='GET',data){
  const [route,query='']=path.split('?');let users=readStore('aq_users',[]);let properties=readStore('aq_properties',null);if(!Array.isArray(properties)){properties=demoProperties;writeStore('aq_properties',properties);}const session=Number(readStore('aq_session',0));const user=users.find(u=>u.id===session)||null;
  if(route==='me'&&method==='GET')return {user:user?{id:user.id,name:user.name,email:user.email}:null};
  if((route==='register'||route==='login')&&method==='POST'){
    const email=String(data.email||'').trim().toLowerCase(),password=String(data.password||'');if(!/^\S+@\S+\.\S+$/.test(email))throw Error('أدخل بريدًا إلكترونيًا صحيحًا.');if(password.length<10)throw Error('كلمة المرور يجب أن تكون 10 أحرف على الأقل.');const digest=await passwordDigest(password);
    let found=users.find(u=>u.email===email);if(route==='register'){const name=String(data.name||'').trim();if(name.length<2)throw Error('أدخل الاسم بشكل صحيح.');if(found)throw Error('يوجد حساب بهذا البريد. جرب تسجيل الدخول.');found={id:Date.now(),name,email,password:digest};users.push(found);writeStore('aq_users',users);}else if(!found||found.password!==digest)throw Error('البريد أو كلمة المرور غير صحيحة.');writeStore('aq_session',found.id);return {ok:true};
  }
  if(route==='logout'&&method==='POST'){writeStore('aq_session',0);return {ok:true};}
  if(route==='properties'&&method==='GET'){
    const q=new URLSearchParams(query);let list=properties.slice().reverse();for(const key of ['city','kind','mode'])if(q.get(key))list=list.filter(p=>p[key]===q.get(key));if(q.get('min'))list=list.filter(p=>p.price>=Number(q.get('min')));if(q.get('max'))list=list.filter(p=>p.price<=Number(q.get('max')));if(q.get('rooms'))list=list.filter(p=>p.rooms>=Number(q.get('rooms')));if(q.get('mine')){if(!user)throw Error('سجّل الدخول أولًا.');list=list.filter(p=>p.user_id===user.id);}const start=Number(q.get('offset')||0);return {items:list.slice(start,start+24),total:list.length};
  }
  if(route==='properties'&&method==='POST'){
    if(!user)throw Error('سجّل الدخول لإضافة عقار.');const phone=String(data.phone||'').replace(/[\s()-]/g,'').replace(/^00/,'+');if(!/^\+[1-9]\d{7,14}$/.test(phone))throw Error('أدخل الهاتف مع رمز الدولة، مثل +963 ثم الرقم دون صفر البداية.');const property={id:Date.now(),user_id:user.id,title:String(data.title).trim(),city:data.city,kind:data.kind,mode:data.mode,price:Number(data.price),area:Number(data.area),rooms:Number(data.rooms),description:String(data.description).trim(),phone,advertiser:user.name};properties.push(property);writeStore('aq_properties',properties);return {id:property.id};
  }
  if(/^properties\/\d+$/.test(route)&&method==='DELETE'){if(!user)throw Error('سجّل الدخول أولًا.');const id=Number(route.split('/')[1]),index=properties.findIndex(p=>p.id===id&&p.user_id===user.id);if(index<0)throw Error('الإعلان غير موجود أو لا تملك صلاحية حذفه.');properties.splice(index,1);writeStore('aq_properties',properties);return {ok:true};}
  throw Error('المسار غير موجود.');
}
async function api(path,method='GET',data){if(STATIC_MODE)return localApi(path,method,data);const res=await fetch('/api/'+path,{method,credentials:'same-origin',headers:method==='GET'?{}:{'Content-Type':'application/json','X-Requested-With':'Aqartkom'},body:data===undefined?undefined:JSON.stringify(data)});let result;try{result=await res.json();}catch{throw Error('تعذر الاتصال بالخادم. أعد المحاولة.');}if(!res.ok)throw Error(result.error||'تعذر إتمام الطلب.');return result;}
function el(tag,text,className){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;}
function fill(select,values,placeholder){select.replaceChildren();if(placeholder){const o=el('option',placeholder);o.value='';select.append(o);}values.forEach(v=>{const o=el('option',v);o.value=v;select.append(o);});}
fill($('#city'),cities,'كل المحافظات');fill($('#type'),kinds,'كل الأنواع');fill($('#propertyForm [name=city]'),cities,'اختر المحافظة');fill($('#propertyForm [name=kind]'),kinds,'اختر النوع');
function contact(p){const wrap=el('div',undefined,'contact');const call=el('a','اتصال');call.href='tel:'+p.phone;call.setAttribute('aria-label','اتصال بالمعلن '+p.advertiser);const wa=el('a','واتساب','wa');wa.href='https://wa.me/'+p.phone.replace(/\D/g,'')+'?text='+encodeURIComponent('مرحبًا، أستفسر عن إعلانكم: '+p.title+' (رقم '+p.id+')');wa.target='_blank';wa.rel='noopener noreferrer';wrap.append(call,wa);return wrap;}
function showDetails(p){const body=$('#detailsBody');body.replaceChildren();const title=el('h2',p.title);title.id='detailsTitle';body.append(title,el('p',p.city+' · '+p.kind),el('p',price(p),'listing-price'),el('p',p.area+' م² · '+p.rooms+' غرف نوم'),el('p',p.description,'details-description'),el('p','المعلن: '+p.advertiser));const phone=el('a',p.phone,'phone');phone.href='tel:'+p.phone;body.append(phone,contact(p));if(me&&p.user_id===me.id){const remove=el('button','حذف إعلاني','danger');remove.onclick=()=>{deleteId=p.id;$('#deleteError').textContent='';$('#detailsDialog').close();$('#deleteDialog').showModal();};body.append(remove);}$('#detailsDialog').showModal();}
function price(p){return Number(p.price).toLocaleString('ar-SY')+' دولار'+(p.mode==='rent'?' / شهر':'');}
function render(){const container=$('#propertyCards');container.replaceChildren();const shown=favoritesOnly?items.filter(p=>favorites.has(p.id)):items;for(const p of shown){const card=el('article',undefined,'card');const top=el('div',undefined,'listing-top');const heart=el('button',favorites.has(p.id)?'♥':'♡','heart');heart.setAttribute('aria-label','حفظ '+p.title+' في المفضلة');heart.setAttribute('aria-pressed',String(favorites.has(p.id)));heart.onclick=()=>{favorites.has(p.id)?favorites.delete(p.id):favorites.add(p.id);try{localStorage.setItem('aq_favorites',JSON.stringify([...favorites]));}catch{toast('المفضلة لهذه الجلسة فقط؛ التخزين غير متاح.');}render();};top.append(el('span',p.mode==='rent'?'للإيجار':'للبيع'),heart);const body=el('div',undefined,'body');body.append(el('h4',p.title),el('div',p.city+' · '+p.kind,'location'),el('div',price(p),'listing-price'));const meta=el('div',undefined,'meta');meta.append(el('span',p.area+' م²'),el('span',p.rooms+' غرف نوم'));body.append(meta,el('div','المعلن: '+p.advertiser,'advertiser'));const phone=el('a',p.phone,'phone');phone.href='tel:'+p.phone;const details=el('button','عرض التفاصيل','detail-button');details.onclick=()=>showDetails(p);body.append(phone,contact(p),details);card.append(top,body);container.append(card);}if(!shown.length){const empty=el('div',undefined,'empty');empty.append(el('h4',favoritesOnly?'لا توجد مفضلة ضمن النتائج المحمّلة':'لا توجد عقارات مطابقة'),el('p',favoritesOnly?'جرّب عرض الكل أو تحميل المزيد من العقارات.':'غيّر خيارات البحث أو أضف أول إعلان.'));const add=el('button','أضف عقارك','goldbtn');add.onclick=openAdd;empty.append(add);container.append(empty);}$('#resultsTitle').textContent=mine?'إعلاناتي':favoritesOnly?'المفضلة':'العقارات المتاحة ('+total+')';$('#moreResults').hidden=offset>=total;$('#favoritesOnly').setAttribute('aria-pressed',String(favoritesOnly));$('#mineOnly').setAttribute('aria-pressed',String(mine));}
async function load(more=false){const id=++requestId;$('#moreResults').disabled=true;try{const low=$('#minPrice').value,high=$('#maxPrice').value;if(low&&high&&Number(low)>Number(high))throw Error('أقل سعر يجب ألا يتجاوز أعلى سعر.');const q=new URLSearchParams({offset:String(more?offset:0)});if(mode)q.set('mode',mode);for(const [key,selector] of [['city','#city'],['kind','#type'],['min','#minPrice'],['max','#maxPrice'],['rooms','#rooms']]){const v=$(selector).value;if(v)q.set(key,v);}if(mine)q.set('mine','1');const result=await api('properties?'+q);if(id!==requestId)return;items=more?[...items,...result.items]:result.items;offset=items.length;total=result.total;render();}catch(e){if(id!==requestId)return;toast(e.message);if(!more){$('#propertyCards').replaceChildren(el('p',e.message,'empty'));}}finally{if(id===requestId)$('#moreResults').disabled=false;}}
function updateMode(value){mode=value;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===value));mine=false;load();}
function openAdd(){pendingAdd=true;if(!me){registration=false;syncAuth();$('#accountDialog').showModal();return;}pendingAdd=false;$('#propertyError').textContent='';$('#propertyDialog').showModal();}
function syncAuth(){$('#accountTitle').textContent=registration?'إنشاء حساب':'تسجيل الدخول';$('#nameLabel').hidden=!registration;$('#nameLabel input').required=registration;$('#accountForm button[type=submit]').textContent=registration?'إنشاء الحساب':'دخول';$('#switchAccount').textContent=registration?'لدي حساب بالفعل':'إنشاء حساب جديد';$('#accountForm [name=password]').autocomplete=registration?'new-password':'current-password';$('#accountError').textContent='';}
async function refreshUser(){me=(await api('me')).user;$('#accountButton').textContent=me?'تسجيل الخروج':'دخول / تسجيل';}
$('#accountButton').onclick=async()=>{if(me){try{await api('logout','POST',{});me=null;mine=false;await refreshUser();await load();toast('تم تسجيل الخروج');}catch(e){toast(e.message);}}else{pendingAdd=false;syncAuth();$('#accountDialog').showModal();}};
$('#switchAccount').onclick=()=>{registration=!registration;syncAuth();};
$('#accountForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{await api(registration?'register':'login','POST',Object.fromEntries(new FormData(e.target)));await refreshUser();$('#accountDialog').close();e.target.reset();if(pendingAdd)openAdd();else toast('تم تسجيل الدخول');}catch(err){$('#accountError').textContent=err.message;}finally{button.disabled=false;}};
$('#propertyForm').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{await api('properties','POST',Object.fromEntries(new FormData(e.target)));$('#propertyDialog').close();e.target.reset();mine=true;favoritesOnly=false;mode='';$('#city').value='';$('#type').value='';$('#minPrice').value='';$('#maxPrice').value='';$('#rooms').value='';await load();toast('تم نشر الإعلان');}catch(err){$('#propertyError').textContent=err.message;}finally{e.submitter.disabled=false;}};
$('#confirmDelete').onclick=async()=>{const button=$('#confirmDelete');button.disabled=true;try{await api('properties/'+deleteId,'DELETE',{});$('#deleteDialog').close();await load();toast('تم حذف الإعلان');}catch(e){$('#deleteError').textContent=e.message;}finally{button.disabled=false;}};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('[data-add]').forEach(b=>b.onclick=openAdd);document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>updateMode(b.dataset.mode));
document.querySelectorAll('a[href="#add"]').forEach(a=>a.onclick=e=>{e.preventDefault();openAdd();});document.querySelectorAll('a[href="#sale"],a[href="#rent"]').forEach(a=>a.onclick=e=>{e.preventDefault();updateMode(a.hash==='#rent'?'rent':'sale');$('#sale').scrollIntoView({behavior:'smooth'});});
document.querySelectorAll('.cat').forEach((old,i)=>{const button=el('button',undefined,'cat');while(old.firstChild)button.append(old.firstChild);old.replaceWith(button);button.onclick=()=>{$('#type').value=kinds[i];load();$('#sale').scrollIntoView({behavior:'smooth'});};});
document.querySelectorAll('.city').forEach(old=>{const name=old.querySelector('span').textContent;const b=el('button',name,'city');old.replaceWith(b);b.onclick=()=>{$('#city').value=name;load();};});
$('#searchButton').onclick=()=>{load();$('#sale').scrollIntoView({behavior:'smooth'});};$('#moreResults').onclick=()=>load(true);$('#favoritesOnly').onclick=()=>{favoritesOnly=!favoritesOnly;render();};$('#mineOnly').onclick=()=>{if(!me){pendingAdd=false;syncAuth();$('#accountDialog').showModal();return;}mine=!mine;mode='';load();};$('#resetFilters').onclick=()=>{mine=false;favoritesOnly=false;mode='';for(const s of ['#city','#type','#minPrice','#maxPrice','#rooms'])$(s).value='';document.querySelectorAll('[data-mode]').forEach(b=>b.classList.remove('active'));load();};
refreshUser().catch(()=>toast('تعذر التحقق من الحساب.')).finally(()=>load());

let installPrompt=null;
if('serviceWorker' in navigator&&window.isSecureContext){navigator.serviceWorker.register('sw.js').catch(()=>{console.warn('Offline page unavailable.');});}
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;});
function installed(){return window.matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;}
$('#installApp').hidden=installed();
window.addEventListener('appinstalled',()=>{installPrompt=null;$('#installApp').hidden=true;toast('تمت إضافة عقارتكم');});
$('#installApp').onclick=async()=>{if(installPrompt){const prompt=installPrompt;installPrompt=null;await prompt.prompt();await prompt.userChoice;}else{$('#installDialog').showModal();}};
