const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let properties=[],converted=[],neighborhoods={};
const ids=()=>[...new Set(JSON.parse(localStorage.getItem('aqartkom_compare')||'[]').map(Number).filter(Number.isFinite))].slice(0,4);
async function fx(amount,from,to){if(from===to)return Number(amount);try{const r=await fetch(`/api/fx/convert?amount=${amount}&from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`),j=await r.json();return r.ok?Number(j.converted_amount??j.amount??amount):Number(amount)}catch{return Number(amount)}}
async function load(){const selected=ids();if(selected.length<2){$('#app').innerHTML='<div class="empty">أضف عقارين على الأقل من صفحات العقارات لبدء المقارنة.</div>';return}const r=await fetch('/api/properties/compare',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:selected,priorities:{mode:$('#priority').value}})}),j=await r.json();if(!r.ok){$('#app').innerHTML=`<div class="empty">${esc(j.error)}</div>`;return}properties=j.data;await refresh()}
async function refresh(){const currency=$('#currency').value;converted=await Promise.all(properties.map(async p=>({...p,converted_price:await fx(p.price,p.currency||'USD',currency),converted_ppsqm:p.area?await fx(Number(p.price)/Number(p.area),p.currency||'USD',currency):null})));await Promise.all(properties.map(async p=>{try{const r=await fetch('/api/properties/'+p.id+'/neighborhood'),j=await r.json();if(r.ok)neighborhoods[p.id]=j.data}catch{}}));scoreAndRender()}
function norm(v,min,max,invert=false){if(v===null||v===undefined)return 40;if(max===min)return 75;const n=(Number(v)-min)/(max-min)*100;return invert?100-n:n}
function scoreAndRender(){const mode=$('#priority').value,price=converted.map(x=>x.converted_price),area=converted.map(x=>Number(x.area||0)),demand=converted.map(x=>Number(neighborhoods[x.id]?.demand_score||0)),pp=converted.map(x=>Number(x.converted_ppsqm||0));converted=converted.map((p,i)=>{const a=norm(area[i],Math.min(...area),Math.max(...area)),cheap=norm(price[i],Math.min(...price),Math.max(...price),true),value=norm(pp[i],Math.min(...pp),Math.max(...pp),true),dem=norm(demand[i],Math.min(...demand),Math.max(...demand)),rooms=Math.min(100,Number(p.rooms||0)*18);const weights=mode==='price'?[.6,.1,.15,.1,.05]:mode==='space'?[.15,.55,.1,.1,.1]:mode==='family'?[.15,.25,.1,.15,.35]:mode==='investment'?[.15,.1,.3,.4,.05]:[.25,.25,.2,.2,.1];return{...p,decision_score:Math.round(cheap*weights[0]+a*weights[1]+value*weights[2]+dem*weights[3]+rooms*weights[4])}}).sort((a,b)=>b.decision_score-a.decision_score);render()}
function render(){const cur=$('#currency').value,best=converted[0];$('#recommendation').className='recommendation show';$('#recommendation').innerHTML=`<h2>الاختيار الأقرب لأولويتك: ${esc(best.title)}</h2><p>درجة الملاءمة ${best.decision_score}/100. التوصية إرشادية وتعتمد على البيانات المتاحة.</p>`;const rows=[['درجة الملاءمة',p=>p.decision_score+'/100','score'],['السعر',p=>Number(p.converted_price).toLocaleString('en-US',{maximumFractionDigits:0})+' '+cur,''],['سعر المتر',p=>p.converted_ppsqm?Number(p.converted_ppsqm).toLocaleString('en-US',{maximumFractionDigits:0})+' '+cur:'—',''],['المساحة',p=>p.area?p.area+' م²':'—',''],['غرف النوم',p=>p.rooms??'—',''],['الحمامات',p=>p.baths??'—',''],['المدينة والحي',p=>esc(p.city)+(p.district?' — '+esc(p.district):''),''],['مؤشر طلب الحي',p=>(neighborhoods[p.id]?.demand_score??'—')+'/100',''],['المشاهدات',p=>p.views_count||0,''],['الاستفسارات',p=>p.inquiries||0,'']];$('#app').innerHTML=`<div class="table-wrap"><table class="compare"><thead><tr><th>المعيار</th>${converted.map((p,i)=>`<th class="property-head ${i===0?'best':''}">${p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.title)}">`:''}<b>${esc(p.title)}</b><small>${esc(p.type)} · ${esc(p.mode)}</small><br><button class="remove" onclick="removeProperty(${p.id})">إزالة</button></th>`).join('')}</tr></thead><tbody>${rows.map(([label,get,cls])=>`<tr><td>${label}</td>${converted.map((p,i)=>`<td class="${i===0?'best ':''}${cls}">${get(p)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function removeProperty(id){localStorage.setItem('aqartkom_compare',JSON.stringify(ids().filter(x=>x!==Number(id))));properties=properties.filter(x=>Number(x.id)!==Number(id));if(properties.length<2)return load();refresh()}
$('#priority').onchange=scoreAndRender;$('#currency').onchange=refresh;load();
