'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let mode='login';
async function api(url,options={}){const r=await fetch(url,{credentials:'same-origin',...options}),j=await r.json();if(!r.ok)throw Error(j.error||'تعذر إكمال الطلب');return j;}
function authMode(value){mode=value;$('authTitle').textContent=mode==='login'?'تسجيل الدخول':'إنشاء حساب جديد';$('nameLabel').hidden=$('phoneLabel').hidden=mode==='login';$('authForm').elements.name.required=mode==='register';$('authForm').elements.password.autocomplete=mode==='login'?'current-password':'new-password';$('message').textContent='';}
$('loginMode').onclick=()=>authMode('login');$('registerMode').onclick=()=>authMode('register');
$('authForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,button=form.querySelector('button');button.disabled=true;$('message').textContent='';try{await api('/api/auth/'+mode,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(form)))});form.reset();const returnTo=new URLSearchParams(location.search).get('return_to');if(returnTo&&/^\/hotels\.html(?:\?hotel=\d+)?$/.test(returnTo)){location.assign(returnTo);return;}await load();}catch(error){$('message').textContent=error.message;}finally{button.disabled=false;}};
$('activate').onclick=async()=>{if(!$('authorized').checked){$('message').textContent='أكد أنك مخوّل بإدارة المنشآت أولًا';return;}$('activate').disabled=true;try{await api('/api/hosts/enroll',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({accepted:true})});await load();}catch(e){$('message').textContent=e.message;}finally{$('activate').disabled=false;}};
$('logout').onclick=async()=>{try{await api('/api/auth/logout',{method:'POST'});await load();}catch(e){$('message').textContent=e.message;}};$('refresh').onclick=load;
async function load(){try{$('message').textContent='';$('dashboard').hidden=true;$('enroll').hidden=true;$('list').innerHTML='';const me=(await api('/api/auth/me')).user;$('auth').hidden=!!me;$('account').hidden=!me;if(!me)return;$('accountName').textContent='مرحبًا '+me.name;$('accountEmail').textContent=me.email;const d=await api('/api/hosts/dashboard');$('enroll').hidden=d.enrolled;$('dashboard').hidden=!d.enrolled;if(!d.enrolled)return;const rows=d.data||[];$('stats').innerHTML=[['منشآتي',rows.length],['منشورة',rows.filter(h=>h.status==='active').length],['حجوزات مفتوحة',rows.reduce((n,h)=>n+Number(h.open_bookings||0),0)],['التقييمات',rows.reduce((n,h)=>n+Number(h.review_count||0),0)]].map(([label,n])=>`<div class="panel"><strong>${n}</strong>${label}</div>`).join('');$('list').innerHTML=rows.map(h=>{const type={hotel:'فندق',furnished_apartment:'شقة مفروشة',farm:'مزرعة للإيجار'}[h.lodging_type]||'فندق',status={active:'منشورة',pending:'بانتظار مراجعة الإدارة',inactive:'متوقفة',rejected:'مرفوضة'}[h.status]||h.status;const img=(h.images||[])[0],url=typeof img==='string'?img:img?.url;return `<article class="panel">${url&&/^\/uploads\/[a-zA-Z0-9._-]+$/.test(url)?`<img src="${esc(url)}" alt="${esc(h.name)}" loading="lazy">`:''}<span class="badge">${esc(type)} · ${esc(status)}</span><h2>${esc(h.name)}</h2><p>${esc(h.city)} · ${Number(h.room_types)} أنواع غرف / وحدات</p><p>${Number(h.review_count)?Number(h.review_score).toFixed(1)+' / 5 من '+Number(h.review_count)+' تقييمات':'لا توجد تقييمات بعد'}</p><div class="actions"><a class="button" href="/hotel-partner.html?hotel=${h.id}">لوحة المنشأة</a>${h.status==='active'?`<a href="/hotels.html?hotel=${h.id}">صفحة العملاء</a>`:''}</div></article>`;}).join('')||'<div class="panel">لم تضف منشأة بعد. ابدأ بإضافة فندق أو شقة مفروشة أو مزرعة.</div>';}catch(e){$('message').textContent=e.message;}}load();
