const $=id=>document.getElementById(id);let selectedSearch={}, selectedHotel=null;
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function nights(a,b){return Math.ceil((new Date(b)-new Date(a))/86400000)}
async function search(){const checkIn=$('checkIn').value,checkOut=$('checkOut').value;const params=new URLSearchParams({q:$('q').value,city:$('city').value,checkIn,checkOut,adults:$('guests').value,rooms:$('rooms').value});const r=await fetch('/api/hotels?'+params);const j=await r.json();selectedSearch={checkIn,checkOut,adults:Number($('guests').value),rooms:Number($('rooms').value)};render(j.data||[])}
function isDemoHotel(h){return String(h?.slug||'').startsWith('aqartkom-demo-hotel-v1-')&&String(h?.name||'').startsWith('تجريبي —');}
function hotelPhotos(h){let values=h?.images;try{if(typeof values==='string')values=JSON.parse(values)}catch(_){values=[]}if(!Array.isArray(values))return [];return values.map(x=>typeof x==='string'?x:x?.url).filter(x=>{if(typeof x!=='string')return false;try{const u=new URL(x,location.origin);return u.protocol==='https:'||(u.origin===location.origin&&u.protocol==='http:')}catch(_){return false}});}
function hotelPhoto(h){const url=hotelPhotos(h)[0];return `<div class="photo"><span aria-hidden="true">🏨</span>${url?`<img src="${esc(url)}" alt="${isDemoHotel(h)?'صورة توضيحية للاختبار فقط':esc(h.name)}" loading="lazy" onerror="this.remove()">`:''}${isDemoHotel(h)?'<span class="demo-badge">تجريبي — للاختبار فقط</span>':''}</div>`;}
function render(rows){$('count').textContent=`${rows.length} فندق`;$('hotels').innerHTML=rows.map(h=>`<article class="card">${hotelPhoto(h)}<div class="cardbody"><h3>${esc(h.name)}</h3>${Number(h.star_rating)>0?`<div class="stars">${'★'.repeat(Math.min(5,Math.round(Number(h.star_rating))))} ${Number(h.star_rating)} نجوم</div>`:''}<div class="meta">📍 ${esc(h.city)} ${h.district?'- '+esc(h.district):''}</div><p>${esc((h.description||'').slice(0,120))}</p><div class="price">يبدأ من ${Number(h.min_price||0).toLocaleString()} ${esc((h.currency||'USD'))}</div><div class="meta">${Number(h.review_count)>0?`⭐ ${esc(h.review_score)} · ${Number(h.review_count)} تقييم`:'لا توجد تقييمات بعد'}</div><br><button onclick="openHotel(${h.id})">عرض الغرف والحجز</button></div></article>`).join('')||'<p>لا توجد فنادق متاحة بهذه الشروط.</p>'}
function hotelVideos(h){return (Array.isArray(h?.videos)?h.videos:[]).filter(v=>/^\/uploads\/[a-zA-Z0-9._-]+$/.test(v.url)).map(v=>`<video controls preload="metadata" src="${esc(v.url)}" ${v.poster_url?`poster="${esc(v.poster_url)}"`:''} style="width:100%;max-height:320px"></video>`).join('')}
async function openHotel(id){const r=await fetch('/api/hotels/'+id);const j=await r.json();if(!r.ok)return alert(j.error||'تعذر التحميل');selectedHotel=j.hotel;$('modal').classList.remove('hidden');$('modalBody').innerHTML=`<h2>${esc(j.hotel.name)}</h2>${hotelPhotos(j.hotel).length?`<div class="hotel-gallery">${hotelPhotos(j.hotel).map(url=>`<img src="${esc(url)}" alt="${isDemoHotel(j.hotel)?'صورة توضيحية للاختبار':esc(j.hotel.name)}" loading="lazy" onerror="this.remove()">`).join('')}</div>`:''}${hotelVideos(j.hotel)}<p>📍 ${esc(j.hotel.city)} ${esc(j.hotel.district||'')}</p><p>${esc(j.hotel.description||'')}</p><h3>الغرف المتاحة</h3><div class="rooms">${j.rooms.map(room=>`<div class="room"><div><b>${esc(room.name)}</b>${hotelPhotos(room).map(url=>`<img src="${esc(url)}" loading="lazy" alt="${esc(room.name)}" style="width:100%;max-height:180px;object-fit:cover">`).join('')}${hotelVideos(room)}<div>${esc(room.room_type)} · ${room.max_guests} ضيوف · ${room.size_m2||'-'} م²</div><strong>${Number(room.price).toLocaleString()} ${esc(room.currency)} / ليلة</strong></div><button onclick="bookingForm(${id},${room.id})">احجز</button></div>`).join('')}</div>`}
async function bookingForm(hotelId,roomId){
  $('modalBody').innerHTML='<p role="status">جارٍ حساب السعر ووسائل الدفع…</p>';
  try{
    const fields={hotel_id:hotelId,room_id:roomId,check_in:selectedSearch.checkIn,check_out:selectedSearch.checkOut,adults:selectedSearch.adults,rooms_count:selectedSearch.rooms};
    const response=await fetch('/api/mobile/hotels/quote?'+new URLSearchParams(fields));const result=await response.json();if(!response.ok)throw Error(result.error||'تعذر حساب السعر');
    const quote=result.data,manual=(quote.payment_methods||[]).find(m=>m.id==='shamcash_manual');
    const key=crypto.randomUUID(),bytes=new Uint8Array(32);crypto.getRandomValues(bytes);const token=Array.from(bytes,n=>n.toString(16).padStart(2,'0')).join('');
    $('modalBody').innerHTML=`<h2>${isDemoHotel(selectedHotel)?'تجربة الحجز — لا توجد إقامة فعلية':'بيانات الحجز والدفع'}</h2><p>${esc(quote.check_in)} → ${esc(quote.check_out)} · ${quote.nights} ليالٍ · ${quote.rooms_count} غرفة</p><p class="booking-total">الإجمالي: <b>${Number(quote.total).toLocaleString('ar')} ${esc(quote.currency)}</b></p><form class="booking" id="bookingForm"><label>اسم الضيف<input name="guest_name" required minlength="2" maxlength="180" autocomplete="name"></label><label>رقم الهاتف<input name="guest_phone" required type="tel" minlength="7" maxlength="80" autocomplete="tel"></label><label>البريد الإلكتروني<input name="guest_email" type="email" maxlength="220" autocomplete="email"></label><label>طريقة الدفع<select name="payment_method" id="paymentMethod"><option value="pay_at_hotel">الدفع عند الوصول</option><option value="shamcash_manual">تحويل عبر شام كاش — مراجعة يدوية</option></select></label><div id="paymentNote" class="payment-note" role="status"></div><label>طلبات خاصة<textarea name="special_requests" maxlength="2000"></textarea></label><button id="confirmBooking">تأكيد الحجز</button><p id="bookingError" role="alert"></p></form>`;
    function updatePayment(){const viaSham=$('paymentMethod').value==='shamcash_manual';$('confirmBooking').disabled=viaSham&&!manual?.available;$('confirmBooking').textContent=viaSham?'إنشاء حجز بانتظار التحويل':'تأكيد الحجز';$('paymentNote').textContent=!viaSham?'تُسدد قيمة الإقامة عند الوصول إلى الفندق.':!manual?.available?(manual?.reason||'بانتظار إعداد حساب الاستلام من الإدارة'):`المبلغ المطلوب تحويله: ${Number(manual.amount).toLocaleString('ar')} ${manual.currency}${manual.exchange_rate?' — بسعر صرف '+Number(manual.exchange_rate).toLocaleString('ar')+' ليرة لكل دولار':''}. يبقى الحجز بانتظار مراجعة الإدارة حتى تؤكد وصول التحويل.`;}
    $('paymentMethod').onchange=updatePayment;updatePayment();
    $('bookingForm').onsubmit=async e=>{
      e.preventDefault();const form=new FormData(e.target),button=$('confirmBooking');button.disabled=true;$('bookingError').textContent='';
      const method=form.get('payment_method');
      const body={...fields,guest_name:form.get('guest_name'),guest_phone:form.get('guest_phone'),guest_email:form.get('guest_email'),special_requests:form.get('special_requests'),payment_method:method,expected_total:quote.total,expected_currency:quote.currency,idempotency_key:key};
      if(method==='shamcash_manual')Object.assign(body,{payment_access_token:token,payment_settings_version:manual?.settings_version,expected_transfer_amount:manual?.amount,expected_transfer_currency:manual?.currency});
      try{const r=await fetch('/api/mobile/hotels/book',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw Error(j.error||'تعذر إنشاء الحجز');
        if(j.manual_payment){$('modalBody').innerHTML=`<div class="success"><h2>أُنشئ الحجز بانتظار التحويل</h2><p>رقم الحجز: <b>${esc(j.data.booking_code)}</b></p><p>انتقل إلى بيانات الاستلام ثم أرسل رقم العملية للمراجعة. لم يُسجل دفع حتى الآن.</p><a class="payment-link" href="${esc(j.manual_payment.checkout_url)}">عرض حساب شام كاش ومتابعة الدفع</a></div>`;}
        else $('modalBody').innerHTML=`<div class="success"><h2>${isDemoHotel(selectedHotel)?'تم تسجيل حجز تجريبي ✓':'تم تأكيد الحجز ✓'}</h2><p>رقم الحجز: <b>${esc(j.data.booking_code)}</b></p><p>الإجمالي: <b>${Number(j.data.total).toLocaleString('ar')} ${esc(j.data.currency)}</b></p><p>${isDemoHotel(selectedHotel)?'سجل اختبار فقط، ولا يؤكد إقامة أو دفعة حقيقية.':'طريقة الدفع: عند الوصول. احتفظ برقم الحجز.'}</p></div>`;
      }catch(error){$('bookingError').textContent=error.message;button.disabled=false;}
    };
  }catch(error){$('modalBody').innerHTML=`<p role="alert">${esc(error.message)}</p><p>أغلق النافذة وراجع التواريخ والأعداد ثم حاول مجددًا.</p>`;}
}
$('hotelSearch').addEventListener('submit',e=>{e.preventDefault();search()});$('close').onclick=()=>$('modal').classList.add('hidden');const now=new Date();$('checkIn').value=new Date(now.getTime()+86400000).toISOString().slice(0,10);$('checkOut').value=new Date(now.getTime()+2*86400000).toISOString().slice(0,10);search();
