const $=id=>document.getElementById(id);let selectedSearch={}, selectedHotel=null;
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function nights(a,b){return Math.ceil((new Date(b)-new Date(a))/86400000)}
let hotelSearchVersion=0;
function updateStayRegion(){
 const city=$('city').value,region=city==='mashta'?'mashta':city==='دمشق'?'damascus':'';
 document.querySelectorAll('[data-stay-region]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.stayRegion===region && (!!region||!city))));
 const url=new URL(location.href);region?url.searchParams.set('region',region):url.searchParams.delete('region');
 $('lodgingType').value?url.searchParams.set('lodging_type',$('lodgingType').value):url.searchParams.delete('lodging_type');history.replaceState(history.state,'',url);
}
async function search(){
 const version=++hotelSearchVersion,checkIn=$('checkIn').value,checkOut=$('checkOut').value;
 const status=$('hotelSearchStatus');status.textContent='جارٍ البحث عن الإقامات…';$('hotels').setAttribute('aria-busy','true');updateStayRegion();
 try{
  if(!checkIn||!checkOut||nights(checkIn,checkOut)<=0)throw Error('اختر تاريخ مغادرة بعد تاريخ الوصول.');
  const city=$('city').value,params=new URLSearchParams({lodging_type:$('lodgingType')?.value||'',q:$('q').value,city:city==='mashta'?'':city,checkIn,checkOut,adults:$('guests').value,rooms:$('rooms').value});
  if(city==='mashta')params.set('region','mashta');if($('includeDemo').checked)params.set('includeDemo','true');
  const r=await fetch('/api/hotels?'+params);const j=await r.json();if(version!==hotelSearchVersion)return;if(!r.ok)throw Error(j.error||'تعذر تحميل الإقامات.');
  selectedSearch={checkIn,checkOut,adults:Number($('guests').value),rooms:Number($('rooms').value)};
  render((j.data||[]).filter(h=>$('includeDemo').checked||!isDemoHotel(h)));status.textContent='';
 }catch(error){if(version!==hotelSearchVersion)return;$('count').textContent='';$('hotels').replaceChildren();status.textContent=error.message||'تعذر الاتصال. أعد البحث للمحاولة مجددًا.';}
 finally{if(version===hotelSearchVersion)$('hotels').setAttribute('aria-busy','false');}
}
function isDemoHotel(h){return String(h?.slug||'').startsWith('aqartkom-demo-hotel-v1-')&&String(h?.name||'').startsWith('تجريبي —');}
function hotelPhotos(h){return MediaGallery.items(h).filter(item=>item.type==='image').map(item=>item.url);}
function hotelPhoto(h){const url=hotelPhotos(h)[0];return `<button type="button" class="photo hotel-open-photo" onclick="openHotel(${Number(h.id)})" aria-label="عرض صور وتفاصيل ${esc(h.name)}"><span aria-hidden="true">🏨</span>${url?`<img src="${esc(url)}" alt="${isDemoHotel(h)?'صورة توضيحية للاختبار فقط':esc(h.name)}" loading="lazy" onerror="this.remove()">`:''}${isDemoHotel(h)?'<span class="demo-badge">تجريبي — للاختبار فقط</span>':''}</button>`;}
function render(rows){$('count').textContent=`${rows.length} منشأة`;$('hotels').innerHTML=rows.map(h=>`<article class="card">${hotelPhoto(h)}<div class="cardbody"><h3><button type="button" class="hotel-name" onclick="openHotel(${Number(h.id)})">${esc(h.name)}</button></h3><span class="meta">${esc({hotel:'فندق',furnished_apartment:'شقة مفروشة',farm:'مزرعة للإيجار',chalet:'شاليه'}[h.lodging_type]||'فندق')}</span>${Number(h.star_rating)>0?`<div class="stars">${'★'.repeat(Math.min(5,Math.round(Number(h.star_rating))))} ${Number(h.star_rating)} نجوم</div>`:''}<div class="meta">📍 ${esc(h.city)} ${h.district?'- '+esc(h.district):''}</div><p>${esc((h.description||'').slice(0,120))}</p><div class="price">يبدأ من ${Number(h.min_price||0).toLocaleString()} ${esc((h.currency||'USD'))}</div><div class="meta">${Number(h.review_count)>0?`⭐ ${esc(h.review_score)} · ${Number(h.review_count)} تقييم`:'لا توجد تقييمات بعد'}</div><br><button onclick="openHotel(${h.id})">عرض الوحدات والحجز</button><div data-listing-kind="hotel" data-listing-id="${esc(h.id)}" data-title="${esc(h.name)}"></div></div></article>`).join('')||'<div class="stay-empty"><h3>لا توجد إقامات مطابقة حاليًا</h3><p>جرّب تواريخ أو منطقة أخرى. إذا كنت صاحب منشأة في مشتى الحلو أو دمشق، يمكنك إرسالها للمراجعة.</p><a href="/host-portal.html">أضف منشأتك</a></div>'}

async function openHotel(id){return showHotelDetails(id);}
async function bookingForm(hotelId,roomId){
  $('modalBody').innerHTML='<p role="status">جارٍ حساب السعر ووسائل الدفع…</p>';
  try{
    const fields={hotel_id:hotelId,room_id:roomId,check_in:selectedSearch.checkIn,check_out:selectedSearch.checkOut,adults:selectedSearch.adults,rooms_count:selectedSearch.rooms};
    const response=await fetch('/api/mobile/hotels/quote?'+new URLSearchParams(fields));const result=await response.json();if(!response.ok)throw Error(result.error||'تعذر حساب السعر');
    const quote=result.data,manual=(quote.payment_methods||[]).find(m=>m.id==='shamcash_manual');
    const key=crypto.randomUUID(),bytes=new Uint8Array(32);crypto.getRandomValues(bytes);const token=Array.from(bytes,n=>n.toString(16).padStart(2,'0')).join('');
    $('modalBody').innerHTML=`<h2>${isDemoHotel(selectedHotel)?'تجربة الحجز — لا توجد إقامة فعلية':'بيانات الحجز والدفع'}</h2><p>${esc(quote.check_in)} → ${esc(quote.check_out)} · ${quote.nights} ليالٍ · ${quote.rooms_count} غرفة</p><p class="booking-total">الإجمالي: <b>${Number(quote.total).toLocaleString('ar')} ${esc(quote.currency)}</b></p><p>تُتاح التقييمات للحجوزات التي أُجريت من حساب مسجّل. <a href="/host-portal.html?return_to=${encodeURIComponent('/hotels.html?hotel='+hotelId)}">الدخول أو إنشاء حساب قبل الحجز</a></p><section class="payment-note"><h3>شروط الإقامة والإلغاء</h3><p style="white-space:pre-wrap">${esc(quote.cancellation_policy||'راجع شروط المنشأة قبل الحجز')}</p></section><form class="booking" id="bookingForm"><label>اسم الضيف<input name="guest_name" required minlength="2" maxlength="180" autocomplete="name"></label><label>رقم الهاتف<input name="guest_phone" required type="tel" minlength="7" maxlength="80" autocomplete="tel"></label><label>البريد الإلكتروني<input name="guest_email" type="email" maxlength="220" autocomplete="email"></label><label>طريقة الدفع<select name="payment_method" id="paymentMethod"><option value="pay_at_hotel">الدفع عند الوصول</option><option value="shamcash_manual">تحويل عبر شام كاش — مراجعة يدوية</option></select></label><div id="paymentNote" class="payment-note" role="status"></div><label>طلبات خاصة<textarea name="special_requests" maxlength="2000"></textarea></label><label><input name="accept_stay_terms" type="checkbox" required> قرأت شروط الإقامة والإلغاء وأوافق عليها.</label><button id="confirmBooking">تأكيد الحجز</button><p id="bookingError" role="alert"></p></form>`;
    function updatePayment(){const viaSham=$('paymentMethod').value==='shamcash_manual';$('confirmBooking').disabled=viaSham&&!manual?.available;$('confirmBooking').textContent=viaSham?'إنشاء حجز بانتظار التحويل':'تأكيد الحجز';$('paymentNote').textContent=!viaSham?'تُسدد قيمة الإقامة عند الوصول إلى الفندق.':!manual?.available?(manual?.reason||'بانتظار إعداد حساب الاستلام من الإدارة'):`المبلغ المطلوب تحويله: ${Number(manual.amount).toLocaleString('ar')} ${manual.currency}${manual.exchange_rate?' — بسعر صرف '+Number(manual.exchange_rate).toLocaleString('ar')+' ليرة لكل دولار':''}. يبقى الحجز بانتظار مراجعة الإدارة حتى تؤكد وصول التحويل.`;}
    $('paymentMethod').onchange=updatePayment;updatePayment();
    $('bookingForm').onsubmit=async e=>{
      e.preventDefault();const form=new FormData(e.target),button=$('confirmBooking');button.disabled=true;$('bookingError').textContent='';
      const method=form.get('payment_method');
      const body={...fields,guest_name:form.get('guest_name'),guest_phone:form.get('guest_phone'),guest_email:form.get('guest_email'),special_requests:form.get('special_requests'),payment_method:method,expected_total:quote.total,expected_terms_version:quote.terms_version,expected_currency:quote.currency,idempotency_key:key};
      if(method==='shamcash_manual')Object.assign(body,{payment_access_token:token,payment_settings_version:manual?.settings_version,expected_transfer_amount:manual?.amount,expected_transfer_currency:manual?.currency});
      try{const r=await fetch('/api/mobile/hotels/book',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw Error(j.error||'تعذر إنشاء الحجز');
        if(j.manual_payment){$('modalBody').innerHTML=`<div class="success"><h2>أُنشئ الحجز بانتظار التحويل</h2><p>رقم الحجز: <b>${esc(j.data.booking_code)}</b></p><p>انتقل إلى بيانات الاستلام ثم أرسل رقم العملية للمراجعة. لم يُسجل دفع حتى الآن.</p><a class="payment-link" href="${esc(j.manual_payment.checkout_url)}">عرض حساب شام كاش ومتابعة الدفع</a></div>`;}
        else $('modalBody').innerHTML=`<div class="success"><h2>${isDemoHotel(selectedHotel)?'تم تسجيل حجز تجريبي ✓':'تم تأكيد الحجز ✓'}</h2><p>رقم الحجز: <b>${esc(j.data.booking_code)}</b></p><p>الإجمالي: <b>${Number(j.data.total).toLocaleString('ar')} ${esc(j.data.currency)}</b></p><p>${isDemoHotel(selectedHotel)?'سجل اختبار فقط، ولا يؤكد إقامة أو دفعة حقيقية.':'طريقة الدفع: عند الوصول. احتفظ برقم الحجز.'}</p></div>`;
      }catch(error){$('bookingError').textContent=error.message;button.disabled=false;}
    };
  }catch(error){$('modalBody').innerHTML=`<p role="alert">${esc(error.message)}</p><p>أغلق النافذة وراجع التواريخ والأعداد ثم حاول مجددًا.</p>`;}
}
const stayParams=new URLSearchParams(location.search);
if(stayParams.get('region')==='mashta')$('city').value='mashta';else if(stayParams.get('region')==='damascus')$('city').value='دمشق';
if(['hotel','farm','furnished_apartment','chalet'].includes(stayParams.get('lodging_type')))$('lodgingType').value=stayParams.get('lodging_type');
document.querySelectorAll('[data-stay-region]').forEach(b=>b.addEventListener('click',()=>{$('city').value=b.dataset.stayRegion==='damascus'?'دمشق':b.dataset.stayRegion;$('q').value='';search();}));
$('city').addEventListener('change',updateStayRegion);$('includeDemo').addEventListener('change',search);
$('hotelSearch').addEventListener('submit',e=>{e.preventDefault();search()});$('close').onclick=closeHotelDetails;const now=new Date();$('checkIn').value=new Date(now.getTime()+86400000).toISOString().slice(0,10);$('checkOut').value=new Date(now.getTime()+2*86400000).toISOString().slice(0,10);search();if(typeof location!=='undefined'){const requested=Number(new URLSearchParams(location.search).get('hotel'));if(Number.isSafeInteger(requested)&&requested>0)openHotel(requested);}

async function loadPublicReviews(id){const box=$('stayReviews');if(!box)return;try{const response=await fetch(`/api/hotels/${id}/reviews`);const d=await response.json();if(!response.ok)throw Error(d.error||'تعذر تحميل التقييمات');if(!box.isConnected)return;box.innerHTML=`<h3>تقييمات الضيوف</h3>${(d.data||[]).map(r=>`<article class="payment-note"><b>${Number(r.rating)} / 5 · ${esc(r.guest_name)}</b>${r.verified_stay?'<small> · إقامة مرتبطة بحجز</small>':''}<h4>${esc(r.title||'')}</h4><p style="white-space:pre-wrap">${esc(r.body)}</p>${r.host_reply?`<p>رد المنشأة: ${esc(r.host_reply)}</p>`:''}</article>`).join('')||'<p>لا توجد تقييمات بعد.</p>'}<div id="reviewFormArea"><p>يمكن للضيف تقييم إقامته بعد المغادرة من الحساب الذي أجرى الحجز.</p></div>`;const eligible=await fetch(`/api/hotels/${id}/review-bookings`);const j=await eligible.json();if(!box.isConnected)return;const area=box.querySelector('#reviewFormArea');if(eligible.status===401){area.innerHTML+=`<a href="/host-portal.html?return_to=${encodeURIComponent('/hotels.html?hotel='+id)}">تسجيل الدخول أو إنشاء حساب</a>`;return;}if(!eligible.ok)throw Error(j.error||'تعذر تحميل حجوزاتك');if(!j.data.length){area.innerHTML+='<p>لا توجد إقامة انتهت ومؤهلة لتقييم جديد في حسابك لهذه المنشأة.</p>';return;}area.innerHTML=`<h4>قيّم إقامتك</h4><form id="stayReviewForm" class="booking"><label>الإقامة<select name="booking_id">${j.data.map(b=>`<option value="${b.id}">${esc(b.booking_code)} · ${esc(String(b.check_out).slice(0,10))}</option>`).join('')}</select></label><label>التقييم<select name="rating"><option value="5">5 — ممتاز</option><option value="4">4 — جيد جدًا</option><option value="3">3 — جيد</option><option value="2">2 — مقبول</option><option value="1">1 — ضعيف</option></select></label><input name="title" maxlength="180" placeholder="عنوان التقييم (اختياري)"><textarea name="body" minlength="3" maxlength="2000" required placeholder="صف تجربتك"></textarea><button>نشر التقييم</button><p id="reviewError" role="alert"></p></form>`;area.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,button=f.querySelector('button');button.disabled=true;try{const r=await fetch(`/api/hotels/${id}/reviews`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(f)))});const result=await r.json();if(!r.ok)throw Error(result.error||'تعذر نشر التقييم');await loadPublicReviews(id);}catch(error){f.querySelector('#reviewError').textContent=error.message;button.disabled=false;}};}catch(e){if(box.isConnected)box.insertAdjacentHTML('beforeend',`<p role="alert">${esc(e.message)}</p>`);}}
