'use strict';
const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const parts=location.hash.slice(1).split(':'),code=parts[0],token=parts[1];
async function api(suffix='',body){const r=await fetch('/api/hotel-manual-payments/'+encodeURIComponent(code)+suffix,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'تعذر تحميل بيانات التحويل');return j;}
async function load(){try{const p=(await api()).data;$('payment').hidden=false;$('refresh').hidden=false;
  const status=p.booking_status==='cancelled'?'الحجز ملغى':({awaiting_transfer:'بانتظار التحويل',pending_review:'بانتظار مراجعة الإدارة',approved:'تم تأكيد استلام الدفعة والحجز',rejected:'رُفض التحويل'})[p.status];
  $('message').textContent=status;$('message').className='notice '+(p.status==='approved'&&p.booking_status!=='cancelled'?'success':p.booking_status==='cancelled'?'error':'');
  $('payment').innerHTML=`<h2>${esc(p.hotel_name)}</h2><p>${esc(p.room_name)} · رقم الحجز <b dir="ltr">${esc(p.booking_code)}</b></p><dl class="details"><dt>قيمة الحجز</dt><dd>${Number(p.booking_total).toLocaleString('ar')} ${esc(p.booking_currency)}</dd><dt>مبلغ التحويل</dt><dd class="amount">${Number(p.amount).toLocaleString('ar')} ${esc(p.currency)}</dd>${p.exchange_rate?`<dt>سعر الصرف المثبت</dt><dd>${Number(p.exchange_rate).toLocaleString('ar')} SYP لكل USD</dd>`:''}${p.transaction_reference?`<dt>رقم العملية</dt><dd dir="ltr">${esc(p.transaction_reference)}</dd>`:''}</dl>${p.review_note?`<p class="notice">ملاحظة الإدارة: ${esc(p.review_note)}</p>`:''}`;
  if(p.status==='awaiting_transfer'&&p.booking_status==='pending'){
    if(p.accepting_transfers){$('payment').insertAdjacentHTML('beforeend',`<hr><h2>حساب الاستلام</h2><p>${esc(p.recipient_label)}</p>${p.recipient?`<div class="account" id="account">${esc(p.recipient)}</div><button id="copyAccount" class="secondary">نسخ الحساب</button>`:''}${p.qr_url?`<img class="qr" src="${esc(p.qr_url)}" alt="رمز حساب الاستلام في شام كاش">`:''}<p class="notice">حوّل المبلغ الموضح بهذه العملة إلى الحساب أعلاه، ثم أدخل رقم العملية. لا يُؤكد الحجز إلا بعد مراجعة الإدارة ووصول المبلغ.</p>`);if($('copyAccount'))$('copyAccount').onclick=async()=>{try{await navigator.clipboard.writeText(p.recipient);$('copyAccount').textContent='نُسخ الحساب';}catch{$('copyAccount').textContent='يمكنك تحديد رقم الحساب ونسخه';}};}
    else $('payment').insertAdjacentHTML('beforeend','<p class="notice">تعليمات التحويل لهذا الطلب متوقفة مؤقتًا. لا تحوّل مبلغًا الآن. إذا سبق أن حوّلت، يمكنك إرسال رقم العملية للمراجعة.</p>');
    $('payment').insertAdjacentHTML('beforeend','<form id="submitTransfer"><label>رقم العملية من تطبيق شام كاش<input id="reference" required minlength="3" maxlength="80" pattern="[A-Za-z0-9٠-٩-]{3,80}" dir="ltr" autocomplete="off"></label><button>إرسال للمراجعة</button><p id="submitMessage" role="alert"></p></form>');
    $('submitTransfer').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{await api('/submit',{transaction_reference:$('reference').value});await load();}catch(error){$('submitMessage').textContent=error.message;button.disabled=false;}};
  } else if(p.status==='pending_review'&&p.booking_status==='pending')$('payment').insertAdjacentHTML('beforeend','<p class="notice">استلمنا رقم العملية. بانتظار تأكيد الإدارة. لا تُكرر التحويل.</p>');
  else if(p.booking_status==='cancelled'&&p.payment_status==='paid')$('payment').insertAdjacentHTML('beforeend','<p class="notice">سُجل دفع سابق لهذا الحجز. إلغاء الحجز لا ينفّذ استردادًا تلقائيًا؛ تواصل مع الإدارة لمتابعته.</p>');
}catch(e){$('message').textContent=e.message;$('message').className='notice error';}}
$('refresh').onclick=load;
if(/^AQH-[A-F0-9]{18}$/.test(code||'')&&/^[a-f0-9]{64}$/.test(token||''))load();else{$('message').textContent='رابط متابعة الدفع غير صحيح. افتح الرابط الذي ظهر بعد إنشاء الحجز.';$('message').className='notice error';}
