bindSyriaLocations(document);
const $=s=>document.querySelector(s),map=L.map('map',{zoomControl:true}).setView([35.0,38.0],7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);
let properties=[],markers=L.layerGroup().addTo(map),drawPoints=[],polygonLayer=null,circleLayer=null,mode='bounds';const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const toast=m=>{const x=$('#toast');x.textContent=m;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2300)};
function polygonFromBounds(){const b=map.getBounds();return[[b.getSouth(),b.getWest()],[b.getNorth(),b.getWest()],[b.getNorth(),b.getEast()],[b.getSouth(),b.getEast()]]}
function filters(){return{city:$('#city').value,district:$('#district').value.trim(),mode:$('#mode').value,type:$('#type').value,minPrice:$('#minPrice').value,maxPrice:$('#maxPrice').value,rooms:$('#rooms').value}}
async function search(){const body={...filters(),polygon:mode==='polygon'&&drawPoints.length>=3?drawPoints:mode==='bounds'?polygonFromBounds():null,center:mode==='circle'&&circleLayer?circleLayer.getLatLng():null,radiusKm:mode==='circle'?Number($('#radius').value):0};$('#summary').textContent='جاري البحث...';try{const r=await fetch('/api/properties/geo-search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)throw Error(j.error);properties=j.data;render();$('.filters').classList.remove('open')}catch(e){toast(e.message||'تعذر البحث')}}
function price(p){return Number(p.price||0).toLocaleString('en-US')+' '+esc(p.currency||'USD')}
function render(){markers.clearLayers();for(const p of properties){if(p.latitude==null||p.longitude==null)continue;const icon=L.divIcon({className:'',html:`<div class="price-pin">${price(p)}</div>`,iconSize:[90,30],iconAnchor:[45,15]});L.marker([Number(p.latitude),Number(p.longitude)],{icon}).addTo(markers).bindPopup(`<b>${esc(p.title)}</b><br>${esc(p.city)}${p.district?' — '+esc(p.district):''}<br><a href="/property.html?id=${p.id}">عرض العقار</a>`)}const averages={};for(const p of properties){const c=p.currency||'USD';(averages[c]??=[]).push(Number(p.price||0))}const av=Object.entries(averages).map(([c,a])=>`${Math.round(a.reduce((s,x)=>s+x,0)/a.length).toLocaleString('en-US')} ${c}`).join(' · ');$('#summary').innerHTML=`<b>${properties.length}</b> عقار في النطاق${av?`<br>متوسط السعر: ${esc(av)}`:''}`;$('#results').innerHTML=properties.slice(0,100).map(p=>`<article class="result">${p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.title)}">`:'<span></span>'}<div><h3>${esc(p.title)}</h3><p>${esc(p.city)}${p.district?' — '+esc(p.district):''} · ${esc(p.type)}</p><b>${price(p)}</b><div class="result-actions"><a href="/property.html?id=${p.id}">التفاصيل</a><button onclick="compare(${p.id})">⇄ مقارنة</button></div></div></article>`).join('')||'<p>لا توجد عقارات مطابقة في هذه المنطقة.</p>';updateCompare()}
function compare(id){let a=[...new Set(JSON.parse(localStorage.getItem('aqartkom_compare')||'[]').map(Number))];if(a.includes(Number(id)))a=a.filter(x=>x!==Number(id));else if(a.length>=4)return toast('يمكن مقارنة أربعة عقارات كحد أقصى');else a.push(Number(id));localStorage.setItem('aqartkom_compare',JSON.stringify(a));toast(a.includes(Number(id))?'أضيف العقار للمقارنة':'أزيل العقار من المقارنة');updateCompare()}
function updateCompare(){const n=JSON.parse(localStorage.getItem('aqartkom_compare')||'[]').length;$('#compareLink').textContent=n?`المقارنة (${n})`:'المقارنة'}
$('#searchBounds').onclick=search;['mode','type','rooms'].forEach(id=>$('#'+id).onchange=search);$('#draw').onclick=()=>{mode='polygon';drawPoints=[];if(polygonLayer)map.removeLayer(polygonLayer);$('#draw').classList.add('active');$('#finish').disabled=false;toast('اضغط نقاط حدود المنطقة على الخريطة')};$('#finish').onclick=()=>{if(drawPoints.length<3)return toast('اختر ثلاث نقاط على الأقل');$('#draw').classList.remove('active');$('#finish').disabled=true;map.fitBounds(polygonLayer.getBounds());search()};$('#circle').onclick=()=>{mode='circle';$('#circle').classList.add('active');toast('اضغط مركز دائرة البحث على الخريطة')};$('#radius').onchange=()=>{if(circleLayer){circleLayer.setRadius(Number($('#radius').value)*1000);search()}};map.on('click',e=>{if(mode==='polygon'&&!$('#finish').disabled){drawPoints.push([e.latlng.lat,e.latlng.lng]);if(polygonLayer)map.removeLayer(polygonLayer);polygonLayer=L.polygon(drawPoints,{color:'#d3a23a'}).addTo(map)}else if(mode==='circle'){if(circleLayer)map.removeLayer(circleLayer);circleLayer=L.circle(e.latlng,{radius:Number($('#radius').value)*1000,color:'#d3a23a'}).addTo(map);map.fitBounds(circleLayer.getBounds());search()}});$('#locate').onclick=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(x=>{map.setView([x.coords.latitude,x.coords.longitude],14);mode='bounds';search()},()=>toast('تعذر تحديد موقعك')):toast('الموقع غير مدعوم');$('#saveArea').onclick=async()=>{const name=prompt('اسم منطقة البحث');if(!name)return;const b=mode==='circle'&&circleLayer?{name,center:{lat:circleLayer.getLatLng().lat,lng:circleLayer.getLatLng().lng},radiusKm:Number($('#radius').value)}:{name,polygon:mode==='polygon'&&drawPoints.length>=3?drawPoints:polygonFromBounds()};try{const r=await fetch('/api/me/search-areas',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});if(r.status===401)return toast('سجّل الدخول أولًا لحفظ المنطقة');if(!r.ok)throw Error();toast('تم حفظ منطقة البحث')}catch{toast('تعذر حفظ المنطقة')}};$('#mobileFilters').onclick=()=>$('.filters').classList.toggle('open');map.on('moveend',()=>{if(mode==='bounds')$('#summary').textContent='اضغط «بحث في هذه المنطقة» لتحديث النتائج.'});updateCompare();search();
