async function api(url, opts={}){const r=await fetch(url,{credentials:'include',headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});if(!r.ok){const x=await r.json().catch(()=>({}));throw new Error(x.error||'تعذر تنفيذ الطلب');}return r.json();}
const app=document.getElementById('app');
let listingStatus='all';
function safeUrl(value){try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)?escapeHtml(u.href):'#'}catch{return '#'}}
async function load(){const [s,l]=await Promise.all([api('/api/admin/market/sources'),api('/api/admin/market/listings?status='+encodeURIComponent(listingStatus))]);app.innerHTML=`<div class="card"><h1>مراقبة السوق العقاري السوري</h1><p class="muted">راجع الإعلانات ومصادرها وتحكم بظهورها. ملخصات مكتب مرعي جُمعت من نتائج البحث العام؛ المزامنة الآلية منفصلة وتتطلب ربط Meta.</p><div class="grid"><div><b>${s.data.filter(x=>x.is_active).length}</b><div class="muted">مصادر نشطة</div></div><div><b>${l.data.length}</b><div class="muted">إعلانات في العرض الحالي</div></div></div><div class="toolbar"><button onclick="syncAll()">🔄 تشغيل المزامنة الآن</button><button onclick="addSource()">＋ إضافة صفحة/حساب</button><button onclick="location.reload()">تحديث</button></div></div><div class="card"><h2>المصادر</h2>${s.data.map(x=>`<div style="padding:10px 0;border-bottom:1px solid #eee"><b>${escapeHtml(x.name)}</b> <span class="pill">${escapeHtml(x.platform)}</span> <span class="muted">${escapeHtml(x.page_id||x.account_id||'')}</span> <small>${x.is_active?'مزامنة مفعّلة':'مزامنة متوقفة'}</small></div>`).join('')||'<p>لا توجد مصادر بعد.</p>'}</div><div class="card"><h2>الإعلانات المستوردة</h2><label>حالة الإعلان <select id="marketStatus">${[['all','الكل'],['pending','بانتظار المراجعة'],['published','منشور'],['approved','معتمد'],['rejected','مخفي / مرفوض']].map(([v,t])=>`<option value="${v}" ${listingStatus===v?'selected':''}>${t}</option>`).join('')}</select></label>${l.data.map(x=>`<article class="listing" style="padding:14px 0;border-bottom:1px solid #eee">${(x.media&&x.media[0]&&x.media[0].url)?`<img src="${safeUrl(x.media[0].url)}" alt="">`:'<div></div>'}<div><h3>${escapeHtml(x.title||'إعلان عقاري')}</h3><div>${escapeHtml(x.description||'')}</div><p class="muted">${escapeHtml(x.advertiser_name||'')} · ${escapeHtml(x.city||'')} ${x.district?('· '+escapeHtml(x.district)) : ''}</p><p><b>${x.price?Number(x.price).toLocaleString('ar-SY')+' '+escapeHtml(x.currency||''):''}</b> ${x.area?('· '+x.area+' م²'):''} ${x.rooms?('· '+x.rooms+' غرف'):''}</p><a href="${safeUrl(x.external_url)}" target="_blank" rel="noopener">المصدر الأصلي</a></div><div><p class="pill">${escapeHtml({published:'منشور',pending:'بانتظار المراجعة',approved:'معتمد',rejected:'مخفي / مرفوض',duplicate:'مكرر'}[x.status]||x.status)}</p>${x.raw_data?.import_batch==='2026-09-16-marei-public-references'&&x.status!=='published'?`<button onclick="publish(${Number(x.id)})">إظهار في قسم المكتب</button>`:''}<button onclick="approve(${Number(x.id)})">اعتماد</button><button onclick="reject(${Number(x.id)})">إخفاء / رفض</button></div></article>`).join('')||'<p>لا توجد إعلانات بهذه الحالة.</p>'}</div>`;document.getElementById('marketStatus').onchange=e=>{listingStatus=e.target.value;load()}}
function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
async function syncAll(){try{const x=await api('/api/admin/market/sync',{method:'POST'});alert(`اكتملت المزامنة: ${x.imported} جديد، ${x.duplicates} مكرر.`);load();}catch(e){alert(e.message)}}
async function approve(id){try{await api('/api/admin/market/listings/'+id,{method:'PATCH',body:JSON.stringify({status:'approved'})});load();}catch(e){alert(e.message)}}
async function publish(id){try{await api('/api/admin/market/listings/'+id,{method:'PATCH',body:JSON.stringify({status:'published'})});load();}catch(e){alert(e.message)}}
async function reject(id){try{await api('/api/admin/market/listings/'+id,{method:'PATCH',body:JSON.stringify({status:'rejected'})});load();}catch(e){alert(e.message)}}
async function addSource(){const platform=prompt('المنصة: facebook أو instagram','facebook');if(!platform)return;const name=prompt('اسم الصفحة/الحساب');if(!name)return;const id=prompt('Page ID أو Instagram Account ID');if(!id)return;try{await api('/api/admin/market/sources',{method:'POST',body:JSON.stringify({platform,name,page_id:platform==='facebook'?id:null,account_id:platform==='instagram'?id:null})});load();}catch(e){alert(e.message)}}
load().catch(e=>{app.textContent=e.message});
