async function api(url, opts={}){const r=await fetch(url,{credentials:'include',headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});if(!r.ok){const x=await r.json().catch(()=>({}));throw new Error(x.error||'تعذر تنفيذ الطلب');}return r.json();}
const app=document.getElementById('app');
async function load(){const [s,l]=await Promise.all([api('/api/admin/market/sources'),api('/api/admin/market/listings?status=pending')]);app.innerHTML=`<div class="card"><h1>مراقبة السوق العقاري السوري</h1><p class="muted">يتم استيراد المحتوى من مصادر Meta التي تم ربطها رسمياً بحسابك. لا يتم تجاوز صلاحيات Facebook/Instagram.</p><div class="grid"><div><b>${s.data.length}</b><div class="muted">مصادر نشطة</div></div><div><b>${l.data.length}</b><div class="muted">إعلانات بانتظار المراجعة</div></div></div><div class="toolbar"><button onclick="syncAll()">🔄 تشغيل المزامنة الآن</button><button onclick="addSource()">＋ إضافة صفحة/حساب</button><button onclick="location.reload()">تحديث</button></div></div><div class="card"><h2>المصادر</h2>${s.data.map(x=>`<div style="padding:10px 0;border-bottom:1px solid #eee"><b>${x.name}</b> <span class="pill">${x.platform}</span> <span class="muted">${x.page_id||x.account_id||''}</span></div>`).join('')||'<p>لا توجد مصادر بعد.</p>'}</div><div class="card"><h2>الإعلانات المستوردة — بانتظار المراجعة</h2>${l.data.map(x=>`<article class="listing" style="padding:14px 0;border-bottom:1px solid #eee">${(x.media&&x.media[0]&&x.media[0].url)?`<img src="${x.media[0].url}" alt="">`:'<div></div>'}<div><h3>${escapeHtml(x.title||'إعلان عقاري')}</h3><div>${escapeHtml(x.description||'')}</div><p class="muted">${escapeHtml(x.advertiser_name||'')} · ${escapeHtml(x.city||'')} ${x.district?('· '+escapeHtml(x.district)) : ''}</p><p><b>${x.price?Number(x.price).toLocaleString('ar-SY')+' '+escapeHtml(x.currency||''):''}</b> ${x.area?('· '+x.area+' م²'):''} ${x.rooms?('· '+x.rooms+' غرف'):''}</p><a href="${x.external_url||'#'}" target="_blank" rel="noopener">المصدر الأصلي</a></div><div><button onclick="approve(${x.id})">اعتماد</button><button onclick="reject(${x.id})">رفض</button></div></article>`).join('')||'<p>لا توجد إعلانات جديدة.</p>'}</div>`}
function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
async function syncAll(){try{const x=await api('/api/admin/market/sync',{method:'POST'});alert(`اكتملت المزامنة: ${x.imported} جديد، ${x.duplicates} مكرر.`);load();}catch(e){alert(e.message)}}
async function approve(id){try{await api('/api/admin/market/listings/'+id,{method:'PATCH',body:JSON.stringify({status:'approved'})});load();}catch(e){alert(e.message)}}
async function reject(id){try{await api('/api/admin/market/listings/'+id,{method:'PATCH',body:JSON.stringify({status:'rejected'})});load();}catch(e){alert(e.message)}}
async function addSource(){const platform=prompt('المنصة: facebook أو instagram','facebook');if(!platform)return;const name=prompt('اسم الصفحة/الحساب');if(!name)return;const id=prompt('Page ID أو Instagram Account ID');if(!id)return;try{await api('/api/admin/market/sources',{method:'POST',body:JSON.stringify({platform,name,page_id:platform==='facebook'?id:null,account_id:platform==='instagram'?id:null})});load();}catch(e){alert(e.message)}}
load();
