(()=>{let deferred=null;const toast=t=>{const el=document.getElementById('toast');if(el){el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}};
if('serviceWorker'in navigator) addEventListener('load',()=>navigator.serviceWorker.register('/service-worker.js').catch(console.error));
const btn=document.getElementById('installApp');addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;if(btn)btn.hidden=false;});
const ios=/iPhone|iPad|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
if(btn&&ios&&!/AqartkomNative/.test(navigator.userAgent)&&!navigator.standalone&&!matchMedia('(display-mode: standalone)').matches){btn.hidden=false;btn.title='مشاركة ثم إضافة إلى الشاشة الرئيسية';}
btn?.addEventListener('click',async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null;btn.hidden=true}else toast('على iPhone: مشاركة ← إضافة إلى الشاشة الرئيسية');});
addEventListener('appinstalled',()=>{if(btn)btn.hidden=true;toast('تم تثبيت عقارتكم كتطبيق');});
const push=document.getElementById('enablePush');push?.addEventListener('click',async()=>{try{if(!('Notification'in window)||!('serviceWorker'in navigator))throw Error('غير مدعوم');const perm=await Notification.requestPermission();if(perm!=='granted')return toast('لم يتم منح إذن الإشعارات');const cfg=await fetch('/api/me/notification-config').then(r=>r.json());const key=cfg?.data?.vapidPublicKey;if(!key)return toast('يلزم ضبط VAPID في الخادم');const reg=await navigator.serviceWorker.ready;const sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64ToUint8Array(key)});const r=await fetch('/api/me/push/subscribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subscription:sub})});if(!r.ok)throw Error((await r.json()).error||'تعذر التسجيل');toast('تم تفعيل إشعارات عقارتكم');}catch(e){toast(e.message==='غير مدعوم'?'الإشعارات غير مدعومة على هذا الجهاز':e.message)}});
function urlBase64ToUint8Array(s){const p='='.repeat((4-s.length%4)%4),b=(s+p).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(b);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
})();
