'use strict';
const $=id=>document.getElementById(id), esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={awaiting_transfer:'بانتظار التحويل',pending_review:'بانتظار المراجعة',approved:'تم اعتماد الاستلام',rejected:'مرفوض'};
let config=null, rows=[], selected=null;
async function api(url,options={}){const r=await fetch(url,{credentials:'same-origin',...options});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'تعذر تنفيذ الطلب');return j;}
function message(text,bad=false){$('message').textContent=text;$('message').className=bad?'notice error':'notice';}
function showSettings(){for(const [id,key]of[['recipient','recipient'],['recipientLabel','recipient_label'],['currency','currency'],['exchangeRate','usd_to_syp_rate']])$(id).value=config[key]??'';$('enabled').checked=config.enabled;preview();rateState();}
function preview(){$('qrPreview').hidden=!config.qr_url;if(config.qr_url)$('qrPreview').src=config.qr_url;else $('qrPreview').removeAttribute('src');}
function rateState(){$('exchangeRate').disabled=$('currency').value!=='SYP';}
async function loadPayments(){rows=(await api('/api/admin/shamcash-manual/payments')).data;$('payments').innerHTML=rows.length?`<table><thead><tr><th>الحجز</th><th>الضيف</th><th>المبلغ المطلوب</th><th>رقم العملية</th><th>الحالة</th><th>المراجعة</th></tr></thead><tbody>${rows.map(p=>`<tr><td>${esc(p.booking_code)}<br><small>${esc(p.hotel_name)}</small></td><td>${esc(p.guest_name)}<br><small dir="ltr">${esc(p.guest_phone)}</small></td><td>${Number(p.amount).toLocaleString('ar')} ${esc(p.currency)}</td><td dir="ltr">${esc(p.transaction_reference||'—')}</td><td><span class="badge ${p.status==='pending_review'?'review':p.status==='approved'?'paid':p.status==='rejected'?'rejected':''}">${esc(labels[p.status])}</span>${p.booking_status==='cancelled'?'<br>الحجز ملغى':''}</td><td>${p.booking_status==='pending'&&['awaiting_transfer','pending_review'].includes(p.status)?`${p.status==='pending_review'?`<button data-id="${p.id}" data-action="approve">مراجعة واعتماد</button>`:''} <button class="secondary" data-id="${p.id}" data-action="reject">رفض</button>`:esc(p.review_note||'—')}</td></tr>`).join('')}</tbody></table>`:'<p>لا توجد تحويلات مسجلة بعد.</p>';
  $('payments').querySelectorAll('[data-action]').forEach(button=>button.onclick=()=>openReview(rows.find(p=>String(p.id)===button.dataset.id),button.dataset.action));
}
function openReview(payment,action){selected={payment,action};$('reviewTitle').textContent=action==='approve'?'تأكيد استلام التحويل':'رفض التحويل وإلغاء الحجز';$('reviewDetails').innerHTML=`<dl class="details"><dt>الحجز</dt><dd>${esc(payment.booking_code)}</dd><dt>المبلغ</dt><dd>${Number(payment.amount).toLocaleString('ar')} ${esc(payment.currency)}</dd><dt>صاحب الحساب</dt><dd>${esc(payment.recipient_label)}</dd><dt>حساب الاستلام</dt><dd dir="ltr">${esc(payment.recipient||'حسب رمز الاستلام')}</dd><dt>رقم العملية</dt><dd dir="ltr">${esc(payment.transaction_reference||'لم يُرسل')}</dd></dl>`;$('confirmLabel').hidden=action!=='approve';$('received').checked=false;$('received').required=action==='approve';$('reviewNote').value='';$('reviewNote').required=action==='reject';$('reviewError').textContent='';$('reviewDialog').showModal();}
$('currency').onchange=rateState;$('closeReview').onclick=()=>$('reviewDialog').close();
$('settingsForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{config=(await api('/api/admin/shamcash-manual/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:config.version,enabled:$('enabled').checked,recipient:$('recipient').value,recipient_label:$('recipientLabel').value,currency:$('currency').value,usd_to_syp_rate:$('exchangeRate').value||null,qr_url:config.qr_url})})).data;showSettings();message(config.enabled?'حُفظت بيانات الاستلام وفُعّل التحويل اليدوي.':'حُفظت الإعدادات. التحويل اليدوي غير مفعّل.');}catch(error){message(error.message,true);}finally{button.disabled=false;}};
$('uploadQr').onclick=async()=>{const file=$('qrFile').files[0];if(!file)return message('اختر صورة رمز الاستلام أولًا.',true);$('uploadQr').disabled=true;try{const form=new FormData();form.append('qr',file);config.qr_url=(await api('/api/admin/shamcash-manual/qr',{method:'POST',body:form})).url;preview();message('رُفعت الصورة. راجع الرمز ثم احفظ الإعدادات.');}catch(e){message(e.message,true);}finally{$('uploadQr').disabled=false;}};
$('removeQr').onclick=()=>{config.qr_url='';preview();message('أزيل الرمز من النموذج. احفظ الإعدادات لتطبيق التغيير.');};
$('refresh').onclick=async()=>{try{await loadPayments();message('حُدثت قائمة التحويلات.');}catch(e){message(e.message,true);}};
$('reviewForm').onsubmit=async e=>{e.preventDefault();$('reviewSubmit').disabled=true;try{await api('/api/admin/shamcash-manual/payments/'+selected.payment.id+'/review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:selected.action,received_confirmed:$('received').checked,note:$('reviewNote').value})});$('reviewDialog').close();await loadPayments();message('حُفظ قرار المراجعة وتحدثت حالة الحجز.');}catch(error){$('reviewError').textContent=error.message;}finally{$('reviewSubmit').disabled=false;}};
(async()=>{try{config=(await api('/api/admin/shamcash-manual/settings')).data;showSettings();await loadPayments();$('adminContent').hidden=false;message(config.enabled?'التحويل اليدوي مفعّل.':'أضف بيانات حساب الاستلام وراجع العملة ثم فعّل التحويل اليدوي.');}catch(e){message(e.message,true);const a=document.createElement('a');a.href='/login.html';a.textContent='تسجيل الدخول بحساب المدير';$('message').after(a);}})();
