'use strict';
const {test} = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs').promises;
const path = require('node:path');
const os = require('node:os');
const {promisify} = require('node:util');
const run = promisify(require('node:child_process').execFile);
const express = require('express');
const {PGlite} = require('@electric-sql/pglite');
const {publicAddress,videoUrl,downloadVideo,prepareVideo} = require('../server/office-video-store');
const {seedOfficeListings,readOfficeListings,enabledBatch} = require('../server/office-listings');

test('video imports reject private networks, credentials and social page URLs',async () => {
  for (const ip of ['127.0.0.1','10.1.2.3','172.16.0.1','192.168.1.1','169.254.169.254','100.64.0.1','0.0.0.0','224.0.0.1','::1','::ffff:127.0.0.1','fc00::1','fe80::1','2002:7f00:1::','2001:db8::1','invalid']) assert.equal(publicAddress(ip),false,ip);
  for (const ip of ['8.8.8.8','1.1.1.1','2606:4700:4700::1111']) assert.equal(publicAddress(ip),true,ip);
  for (const url of ['file:///etc/passwd','http://example.com/a.mp4','https://u:p@example.com/a.mp4','https://example.com:8080/a.mp4','https://www.facebook.com/reel/123/','https://youtu.be/abc']) assert.throws(() => videoUrl(url));
  assert.equal(videoUrl('https://files.example.com/a.mp4?signature=abc').search,'?signature=abc');
  await assert.rejects(() => downloadVideo('https://127.0.0.1/video.mp4',path.join(os.tmpdir(),'office-video-denied-'+Date.now())),/غير مسموح/);
});

test('direct downloads pin DNS, save bytes, and recheck redirect destinations',async t => {
  const temp = await fs.mkdtemp(path.join(os.tmpdir(),'office-download-test-'));
  t.after(() => fs.rm(temp,{recursive:true,force:true}));
  const dns = require('node:dns').promises, https = require('node:https');
  const {Readable} = require('node:stream'), {EventEmitter} = require('node:events');
  const payload = Buffer.from('test video response');
  let redirect = false, oversized = false, calls = 0;
  t.mock.method(dns,'lookup',async () => [{address:'8.8.8.8',family:4}]);
  t.mock.method(https,'get',(url,options,callback) => {
    calls++;
    options.lookup(url.hostname,{all:true},(error,addresses) => { assert.equal(error,null); assert.deepEqual(addresses,[{address:'8.8.8.8',family:4}]); });
    const response = Readable.from([payload]);
    response.statusCode = redirect ? 302 : 200;
    response.headers = redirect ? {location:'https://127.0.0.1/private.mp4'} : {'content-type':'video/mp4','content-length':oversized ? 101*1024*1024 : payload.length};
    const request = new EventEmitter(); request.setTimeout = () => request;
    process.nextTick(() => callback(response)); return request;
  });
  const destination = path.join(temp,'video.mp4');
  await downloadVideo('https://files.example/video.mp4',destination);
  assert.deepEqual(await fs.readFile(destination),payload);
  redirect = true; const before = calls;
  await assert.rejects(() => downloadVideo('https://files.example/redirect',path.join(temp,'redirect.mp4')),/غير مسموح/);
  assert.equal(calls,before+1);
  redirect = false; oversized = true;
  await assert.rejects(() => downloadVideo('https://files.example/large',path.join(temp,'large.mp4')),/100/);
  assert.deepEqual(await fs.readdir(temp),['video.mp4']);
});

test('admin upload persists playable video and poster, rejects bad replacements and survives reseeding',async t => {
  const temp = await fs.mkdtemp(path.join(os.tmpdir(),'office-video-test-'));
  t.after(() => fs.rm(temp,{recursive:true,force:true}));
  const uploads = path.join(temp,'uploads'); await fs.mkdir(uploads);
  const fixture = path.join(temp,'source.mp4');
  await run('ffmpeg',['-v','error','-f','lavfi','-i','color=c=blue:s=128x96:r=12','-f','lavfi','-i','sine=frequency=440:sample_rate=44100','-t','1.5','-c:v','libx264','-pix_fmt','yuv420p','-c:a','aac','-threads','1','-y',fixture]);
  const webm = path.join(temp,'source.webm'), converted = path.join(temp,'converted.mp4');
  await run('ffmpeg',['-v','error','-i',fixture,'-c:v','libvpx-vp9','-c:a','libopus','-threads','1','-y',webm]);
  const convertedInfo = await prepareVideo(webm,converted,path.join(temp,'converted.jpg'));
  assert.equal(convertedInfo.has_audio,true); assert.equal(convertedInfo.hasPoster,true);
  const convertedProbe = JSON.parse((await run('ffprobe',['-v','error','-show_streams','-of','json',converted])).stdout);
  assert.equal(convertedProbe.streams.find(s => s.codec_type === 'video').codec_name,'h264');
  assert.equal(convertedProbe.streams.find(s => s.codec_type === 'video').width,128);
  assert.equal(convertedProbe.streams.find(s => s.codec_type === 'audio').codec_name,'aac');
  const db = new PGlite(); await db.waitReady; t.after(() => db.close());
  await db.exec(await fs.readFile(path.join(__dirname,'../server/db/schema.sql'),'utf8'));
  const pool = {query:(...a) => db.query(...a),connect:async() => ({query:(...a) => db.query(...a),release(){}})};
  await seedOfficeListings(pool,enabledBatch);
  const item = (await readOfficeListings(pool))[0];
  const app = express(); app.use(express.json()); app.use('/uploads',express.static(uploads));
  require('../server/office-videos')(app,{pool,uploadDir:uploads,requireAdmin:(req,res,next) => req.get('x-test-admin') === 'yes' ? next() : res.sendStatus(401)});
  const server = app.listen(0,'127.0.0.1'); await new Promise(r => server.once('listening',r)); t.after(() => new Promise(r => server.close(r)));
  const base = 'http://127.0.0.1:'+server.address().port;
  const headers = {'x-test-admin':'yes'};
  async function upload(bytes,admin = true,id = item.id) {
    const form = new FormData(); form.append('video',new Blob([bytes],{type:'video/mp4'}),'office.mp4');
    return fetch(base+'/api/admin/office-videos/'+id+'/upload',{method:'POST',headers:admin?headers:{},body:form});
  }
  const clip = await fs.readFile(fixture);
  assert.equal((await upload(clip,false)).status,401);
  assert.deepEqual(await fs.readdir(uploads),[]);
  assert.equal((await upload(clip,true,99999)).status,404);
  const response = await upload(clip), saved = await response.json();
  assert.equal(response.status,201,JSON.stringify(saved));
  assert.equal(saved.data.has_audio,true);
  assert.match(saved.data.url,/^\/uploads\/office-[a-f0-9]{32}\.mp4$/);
  assert.match(saved.data.poster,/\.jpg$/);
  assert.ok((await fs.stat(path.join(temp,saved.data.url))).size > 0);
  const range = await fetch(base+saved.data.url,{headers:{Range:'bytes=0-31'}});
  assert.equal(range.status,206); assert.equal((await range.arrayBuffer()).byteLength,32);
  const before = (await readOfficeListings(pool)).find(p => p.id === item.id);
  assert.equal(before.hosted_video.url,saved.data.url); assert.equal(before.external_url,item.external_url);
  const failed = await upload(Buffer.from('<script>not video</script>')); assert.equal(failed.status,400);
  assert.equal((await readOfficeListings(pool)).find(p => p.id === item.id).hosted_video.url,saved.data.url);
  const blocked = await fetch(base+'/api/admin/office-videos/'+item.id+'/import',{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({url:'https://www.facebook.com/reel/123/'})});
  assert.equal(blocked.status,400); assert.match((await blocked.json()).error,/رابط صفحة/);
  const foreign = await fetch(base+'/api/admin/office-videos/'+item.id+'/import',{method:'POST',headers:{...headers,origin:'https://other.example','content-type':'application/json'},body:'{}'}); assert.equal(foreign.status,403);
  await seedOfficeListings(pool,enabledBatch);
  assert.equal((await readOfficeListings(pool)).find(p => p.id === item.id).hosted_video.url,saved.data.url);
  const replacement = await upload(clip); assert.equal(replacement.status,201);
  const updated = (await replacement.json()).data;
  assert.notEqual(updated.url,saved.data.url);
  await assert.rejects(() => fs.stat(path.join(temp,saved.data.url)),{code:'ENOENT'});
  assert.equal((await fs.readdir(uploads)).length,2);
  assert.deepEqual(await fs.readdir(path.join(temp,'private_uploads/office-video-tmp')),[]);
  const vm = require('node:vm'), window = {};
  vm.runInNewContext(await fs.readFile(path.join(__dirname,'../office-card.js'),'utf8'),{window,URL});
  const html = window.officeListingCard({...before,hosted_video:updated});
  // The card opens the in-page player, retaining the replaced media URL.
  const playData=html.match(/data-property-video="([^"]+)"/);
  assert.ok(playData,'The uploaded clip must have a play control');
  const media=JSON.parse(playData[1].replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&'));
  assert.equal(media.url,updated.url);
  assert.equal(require('../video-player').resolveVideo(media.url).type,'file');
  assert.ok(html.includes('src="'+updated.poster+'"'));
});
