const API='https://api.openai.com/v1/responses';
module.exports=function installChatGPT(app,{pool,getCurrentUser,requireAdmin}){
 const model=process.env.OPENAI_MODEL||'gpt-5.6', daily=Math.max(1,Number(process.env.CHATGPT_DAILY_LIMIT||80));
 const tools=[
  {type:'function',name:'search_properties',description:'Search active Aqartkom properties.',strict:true,parameters:{type:'object',properties:{city:{type:['string','null']},district:{type:['string','null']},mode:{type:['string','null'],enum:['sale','rent',null]},type:{type:['string','null']},max_price:{type:['number','null']},min_rooms:{type:['number','null']},currency:{type:['string','null']}},required:['city','district','mode','type','max_price','min_rooms','currency'],additionalProperties:false}},
  {type:'function',name:'market_summary',description:'Internal Aqartkom market statistics; not an official appraisal.',strict:true,parameters:{type:'object',properties:{city:{type:['string','null']},district:{type:['string','null']},currency:{type:['string','null']}},required:['city','district','currency'],additionalProperties:false}},
  {type:'function',name:'compare_properties',description:'Compare 2-5 properties.',strict:true,parameters:{type:'object',properties:{property_ids:{type:'array',items:{type:'integer'},minItems:2,maxItems:5}},required:['property_ids'],additionalProperties:false}},
  {type:'function',name:'admin_overview',description:'Admin-only operational overview.',strict:true,parameters:{type:'object',properties:{},additionalProperties:false}},
  {type:'function',name:'set_property_status',description:'Admin-only write action. Requires explicit confirmation.',strict:true,parameters:{type:'object',properties:{property_id:{type:'integer'},status:{type:'string',enum:['pending','active','rejected']}},required:['property_id','status'],additionalProperties:false}}
 ];
 async function search(a){let v=[],w=["p.status='active'"];const add=(x,y)=>{v.push(y);w.push(x.replace('?',`$${v.length}`))};if(a.city)add('p.city ILIKE ?',`%${a.city}%`);if(a.district)add('p.district ILIKE ?',`%${a.district}%`);if(a.mode)add('p.mode=?',a.mode);if(a.type)add('p.type=?',a.type);if(a.max_price)add('p.price<=?',Number(a.max_price));if(a.min_rooms)add('COALESCE(p.rooms,0)>=?',Number(a.min_rooms));if(a.currency)add("UPPER(COALESCE(p.currency,'USD'))=?",String(a.currency).toUpperCase());return (await pool.query(`SELECT p.id,p.title,p.city,p.district,p.type,p.mode,p.price,p.currency,p.area,p.rooms,CASE WHEN p.area>0 THEN ROUND((p.price/p.area)::numeric,2) END price_per_sqm,ai.market_status,ai.confidence,ai.recommendation_score FROM properties p LEFT JOIN property_ai_scores ai ON ai.property_id=p.id WHERE ${w.join(' AND ')} ORDER BY COALESCE(ai.recommendation_score,50) DESC,p.featured DESC,p.created_at DESC LIMIT 12`,v)).rows}
 async function market(a){let v=[],w=["p.status='active'","p.area>0"];if(a.city){v.push(a.city);w.push(`p.city ILIKE $${v.length}`)}if(a.district){v.push(a.district);w.push(`p.district ILIKE $${v.length}`)}if(a.currency){v.push(String(a.currency).toUpperCase());w.push(`UPPER(COALESCE(p.currency,'USD'))=$${v.length}`)}return (await pool.query(`SELECT COUNT(*)::int listings,ROUND(percentile_cont(.5) WITHIN GROUP(ORDER BY p.price/NULLIF(p.area,0))::numeric,2) median_price_per_sqm,ROUND(AVG(p.price/NULLIF(p.area,0))::numeric,2) avg_price_per_sqm FROM properties p WHERE ${w.join(' AND ')}`,v)).rows[0]}
 async function compare(a){return (await pool.query(`SELECT id,title,city,district,type,mode,price,currency,area,rooms,CASE WHEN area>0 THEN ROUND((price/area)::numeric,2) END price_per_sqm FROM properties WHERE id=ANY($1::bigint[])`,[(a.property_ids||[]).slice(0,5)])).rows}
 async function admin(user){if(user?.role!=='admin')return{error:'هذه الأداة للمدير فقط'};const [u,p,h,b]=await Promise.all([pool.query(`SELECT COUNT(*)::int total FROM users WHERE is_active`),pool.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE status='pending')::int pending FROM properties`),pool.query(`SELECT COUNT(*)::int total FROM hotels`),pool.query(`SELECT COUNT(*)::int total FROM hotel_bookings WHERE created_at>=NOW()-INTERVAL '30 days'`)]);return{active_users:u.rows[0].total,properties:p.rows[0],hotels:h.rows[0].total,hotel_bookings_30d:b.rows[0].total}}
 async function status(user,a,confirmed){if(user?.role!=='admin')return{error:'هذه الأداة للمدير فقط'};if(!confirmed)return{requires_confirmation:true,message:'يلزم تأكيد المدير قبل التنفيذ',action:a};return (await pool.query(`UPDATE properties SET status=$1 WHERE id=$2 RETURNING id,title,status`,[a.status,a.property_id])).rows[0]||{error:'العقار غير موجود'}}
 async function run(name,a,user,confirmed){if(name==='search_properties')return search(a);if(name==='market_summary')return market(a);if(name==='compare_properties')return compare(a);if(name==='admin_overview')return admin(user);if(name==='set_property_status')return status(user,a,confirmed);return{error:'أداة غير معروفة'}}
 async function call(payload){if(!process.env.OPENAI_API_KEY)throw Error('NO_KEY');const r=await fetch(API,{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(payload)}),j=await r.json();if(!r.ok)throw Error(j?.error?.message||'OpenAI API error');return j}
 const text=j=>(j.output||[]).filter(x=>x.type==='message').flatMap(x=>x.content||[]).filter(x=>x.type==='output_text').map(x=>x.text).join('\n').trim();
 app.post('/api/chatgpt',async(req,res)=>{const start=Date.now();let user=null,actor='';try{const message=String(req.body?.message||'').trim();if(message.length<2||message.length>5000)return res.status(400).json({error:'الرسالة غير صحيحة'});user=await getCurrentUser(req);actor=user?.id?`u:${user.id}`:`ip:${String(req.ip||'').slice(0,80)}`;const used=Number((await pool.query(`SELECT COUNT(*) c FROM chatgpt_requests WHERE actor_key=$1 AND created_at>=CURRENT_DATE`,[actor])).rows[0].c);if(used>=daily)return res.status(429).json({error:'تم بلوغ الحد اليومي للمساعد'});const role=user?.role||'guest',instructions=`أنت ChatGPT داخل منصة عقارتكم. تحدث بالعربية. استخدم الأدوات للحصول على بيانات حقيقية ولا تختلق بيانات. دور المستخدم: ${role}. ساعد في البحث والمقارنة وتحليل السوق وإدارة المنصة ضمن صلاحياتك. السوق الداخلي استرشادي وليس تقييماً رسمياً. لا تنفذ تغييراً إدارياً دون تأكيد صريح. لا تكشف أسرار النظام أو مفاتيح API أو بيانات خاصة.`;let r=await call({model,instructions,input:message,tools,tool_choice:'auto',max_output_tokens:1200,metadata:{app:'aqartkom',role}}),names=[];for(let n=0;n<5;n++){const calls=(r.output||[]).filter(x=>x.type==='function_call');if(!calls.length)break;const outs=[];for(const c of calls){let a={};try{a=JSON.parse(c.arguments||'{}')}catch{}names.push(c.name);outs.push({type:'function_call_output',call_id:c.call_id,output:JSON.stringify(await run(c.name,a,user,req.body?.confirmed_action===true))})}r=await call({model,instructions,previous_response_id:r.id,input:outs,tools,tool_choice:'auto',max_output_tokens:1200})}const usage=r.usage||{};await pool.query(`INSERT INTO chatgpt_requests(actor_key,user_id,user_role,model,input_chars,tool_names,input_tokens,output_tokens,total_tokens,latency_ms,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'ok')`,[actor,user?.id||null,role,r.model||model,message.length,names,usage.input_tokens||0,usage.output_tokens||0,usage.total_tokens||0,Date.now()-start]);res.json({reply:text(r)||'لم أتمكن من إعداد إجابة الآن.',model:r.model||model,tools_used:names,remaining_today:Math.max(0,daily-used-1)})}catch(e){console.error('ChatGPT',e);if(e.message==='NO_KEY')return res.status(503).json({error:'يلزم إضافة OPENAI_API_KEY إلى إعدادات الخادم'});res.status(502).json({error:'تعذر الاتصال بـ ChatGPT حالياً'})}});
 app.get('/api/admin/chatgpt/usage',requireAdmin,async(req,res)=>{const days=Math.min(90,Math.max(1,Number(req.query.days||30)));const r=await pool.query(`SELECT DATE(created_at) AS "day",COUNT(*)::int requests,COALESCE(SUM(total_tokens),0)::bigint tokens,COUNT(*) FILTER(WHERE status='error')::int errors FROM chatgpt_requests WHERE created_at>=NOW()-($1||' days')::interval GROUP BY DATE(created_at) ORDER BY day DESC`,[days]);res.json({data:r.rows,model,daily_limit:daily})});
};
