'use strict';
function hostPath(req){const p=req.path||'';if(/^\/api\/office\/hotels(?:\/\d+)?$/.test(p))return true;if(/^\/api\/office\/hotel-rooms\/\d+(?:\/(rates|blocks))?$/.test(p)||/^\/api\/office\/hotel-(bookings|promotions)\/\d+$/.test(p))return true;return /^\/api\/office\/hotels\/\d+\/(rooms(?:\/\d+(?:\/(images|videos|media))?)?|bookings|reviews(?:\/\d+\/reply)?|stay-settings|images|videos|media|promotions|calendar|availability)$/.test(p)||(/^\/api\/office\/hotels\/\d+\/finance$/.test(p)&&req.method==='GET');}
const types=['hotel','furnished_apartment','farm'];
function register(app,{pool,requireAuth,requireOfficeMember,ownedHotel}){
 app.post('/api/hosts/enroll',requireAuth,async(req,res)=>{try{if(req.body.accepted!==true)return res.status(400).json({error:'أكد أنك مخوّل بإدارة المنشآت التي ستضيفها'});await pool.query('UPDATE users SET is_host=TRUE,updated_at=NOW() WHERE id=$1',[req.user.id]);res.json({ok:true});}catch(e){res.status(500).json({error:'تعذر تفعيل حساب المستضيف'});}});
 app.get('/api/hosts/dashboard',requireAuth,async(req,res)=>{try{
  if(!req.user.is_host&&!['agent','admin'].includes(req.user.role))return res.json({enrolled:false,data:[]});
  // Admins have their central management view; this personal dashboard is restricted to their own establishments.
  const rows=(await pool.query(`SELECT h.*, (SELECT COUNT(*)::int FROM hotel_rooms r WHERE r.hotel_id=h.id) room_types,
  (SELECT COUNT(*)::int FROM hotel_bookings b WHERE b.hotel_id=h.id AND b.status IN ('pending','confirmed')) open_bookings,
  (SELECT AVG(r.rating) FROM hotel_reviews r WHERE r.hotel_id=h.id AND r.status='published') review_score,
  (SELECT COUNT(*)::int FROM hotel_reviews r WHERE r.hotel_id=h.id AND r.status='published') review_count
  FROM hotels h WHERE h.owner_id=$1 OR ($3::boolean AND h.office_id IN (SELECT o.id FROM offices o WHERE o.owner_id=$1 OR o.id=$2)) ORDER BY h.created_at DESC`,[req.user.id,req.user.office_id||null,['agent','admin'].includes(req.user.role)])).rows;
  res.json({enrolled:true,data:rows});
 }catch(e){res.status(500).json({error:'تعذر تحميل لوحة المستضيف'});}});
 app.patch('/api/office/hotels/:id/stay-settings',requireOfficeMember,async(req,res)=>{try{
  if(!await ownedHotel(req.params.id,req.office))return res.status(404).json({error:'المنشأة غير موجودة'});
  const b=req.body,hours=Number(b.free_cancel_hours),terms=String(b.rental_terms||'').trim(),policy=String(b.cancellation_policy||'').trim();
  if(!Number.isSafeInteger(Number(b.terms_version))||Number(b.terms_version)<1||!types.includes(b.lodging_type)||!Number.isInteger(hours)||hours<0||hours>720||terms.length>3000||policy.length>2000||![b.check_in_time,b.check_out_time].every(x=>/^([01]\d|2[0-3]):[0-5]\d$/.test(String(x))))return res.status(400).json({error:'راجع نوع المنشأة ومواعيد الدخول والخروج وشروط الإلغاء (0 إلى 720 ساعة)'});
  const row=(await pool.query(`UPDATE hotels SET lodging_type=$1,rental_terms=$2,cancellation_policy=$3,free_cancel_hours=$4,check_in_time=$5,check_out_time=$6,terms_version=terms_version+1,updated_at=NOW() WHERE id=$7 AND terms_version=$8 RETURNING *`,[b.lodging_type,terms,policy,hours,b.check_in_time,b.check_out_time,req.params.id,Number(b.terms_version)])).rows[0];
  if(!row)return res.status(409).json({error:'تغيرت الشروط؛ حدّث الصفحة قبل حفظها'});res.json({data:row});
 }catch(e){res.status(500).json({error:'تعذر حفظ شروط المنشأة'});}});
 app.get('/api/hotels/:id/reviews',async(req,res)=>{try{const rows=(await pool.query(`SELECT r.id,r.rating,r.title,r.body,r.guest_name,r.created_at,r.host_reply,r.replied_at,(r.booking_id IS NOT NULL) verified_stay FROM hotel_reviews r JOIN hotels h ON h.id=r.hotel_id WHERE h.id=$1 AND h.status='active' AND r.status='published' ORDER BY r.created_at DESC LIMIT 100`,[req.params.id])).rows;res.json({data:rows});}catch(e){res.status(400).json({error:'تعذر تحميل التقييمات'});}});
 app.get('/api/hotels/:id/review-bookings',requireAuth,async(req,res)=>{try{const rows=(await pool.query(`SELECT b.id,b.booking_code,b.check_in,b.check_out FROM hotel_bookings b JOIN hotels h ON h.id=b.hotel_id WHERE b.hotel_id=$1 AND b.user_id=$2 AND h.owner_id IS DISTINCT FROM $2 AND NOT EXISTS(SELECT 1 FROM offices o WHERE o.id=h.office_id AND (o.owner_id=$2 OR o.id=(SELECT office_id FROM users WHERE id=$2))) AND h.status='active' AND b.status IN ('confirmed','completed') AND ((b.check_out+COALESCE(b.stay_terms_snapshot->>'check_out_time',h.check_out_time,'12:00')::time) AT TIME ZONE 'Asia/Damascus')<=NOW() AND NOT EXISTS(SELECT 1 FROM hotel_reviews r WHERE r.booking_id=b.id) ORDER BY b.check_out DESC LIMIT 50`,[req.params.id,req.user.id])).rows;res.json({data:rows});}catch(e){res.status(400).json({error:'تعذر تحميل الإقامات المؤهلة للتقييم'});}});
 app.post('/api/hotels/:id/reviews',requireAuth,async(req,res)=>{let db,transaction=false;try{
  const b=req.body,booking=Number(b.booking_id),rating=Number(b.rating),body=String(b.body||'').trim(),title=String(b.title||'').trim();
  if(!Number.isSafeInteger(booking)||booking<1||!Number.isInteger(rating)||rating<1||rating>5||body.length<3||body.length>2000||title.length>180)return res.status(400).json({error:'اختر إقامة وتقييمًا من 1 إلى 5 واكتب تعليقًا من 3 إلى 2000 حرف'});
  db=await pool.connect();await db.query('BEGIN');transaction=true;await db.query('SELECT pg_advisory_xact_lock($1)',[booking]);
  const stay=(await db.query(`SELECT b.id FROM hotel_bookings b JOIN hotels h ON h.id=b.hotel_id WHERE b.id=$1 AND b.hotel_id=$2 AND b.user_id=$3 AND h.owner_id IS DISTINCT FROM $3 AND NOT EXISTS(SELECT 1 FROM offices o WHERE o.id=h.office_id AND (o.owner_id=$3 OR o.id=(SELECT office_id FROM users WHERE id=$3))) AND h.status='active' AND b.status IN ('confirmed','completed') AND ((b.check_out+COALESCE(b.stay_terms_snapshot->>'check_out_time',h.check_out_time,'12:00')::time) AT TIME ZONE 'Asia/Damascus')<=NOW() FOR UPDATE OF b`,[booking,req.params.id,req.user.id])).rows[0];
  if(!stay){await db.query('ROLLBACK');transaction=false;return res.status(403).json({error:'التقييم متاح لصاحب حجز مسجّل بحسابه بعد انتهاء الإقامة، ولا يشمل الحجوزات الملغاة'});}
  if((await db.query('SELECT id FROM hotel_reviews WHERE booking_id=$1',[booking])).rows[0]){await db.query('ROLLBACK');transaction=false;return res.status(409).json({error:'سبق تقييم هذه الإقامة'});}
  const result=await db.query("INSERT INTO hotel_reviews(hotel_id,booking_id,user_id,guest_name,rating,title,body,status) VALUES($1,$2,$3,$4,$5,$6,$7,'published') RETURNING id,rating",[req.params.id,booking,req.user.id,req.user.name,rating,title,body]);await db.query('COMMIT');transaction=false;res.status(201).json({data:result.rows[0]});
 }catch(e){if(transaction)await db.query('ROLLBACK');res.status(500).json({error:'تعذر حفظ التقييم'});}finally{db?.release();}});
 app.get('/api/office/hotels/:id/reviews',requireOfficeMember,async(req,res)=>{try{if(!await ownedHotel(req.params.id,req.office))return res.status(404).json({error:'المنشأة غير موجودة'});res.json({data:(await pool.query("SELECT id,rating,title,body,guest_name,created_at,host_reply FROM hotel_reviews WHERE hotel_id=$1 AND status='published' ORDER BY created_at DESC LIMIT 100",[req.params.id])).rows});}catch(e){res.status(500).json({error:'تعذر تحميل التقييمات'});}});
 app.patch('/api/office/hotels/:id/reviews/:reviewId/reply',requireOfficeMember,async(req,res)=>{try{if(!await ownedHotel(req.params.id,req.office))return res.status(404).json({error:'المنشأة غير موجودة'});const reply=String(req.body.reply||'').trim();if(!reply||reply.length>1000)return res.status(400).json({error:'اكتب ردًا لا يتجاوز 1000 حرف'});const row=(await pool.query("UPDATE hotel_reviews SET host_reply=$1,replied_at=NOW() WHERE id=$2 AND hotel_id=$3 AND status='published' RETURNING id,host_reply",[reply,req.params.reviewId,req.params.id])).rows[0];if(!row)return res.status(404).json({error:'التقييم غير موجود'});res.json({data:row});}catch(e){res.status(500).json({error:'تعذر حفظ الرد'});}});
}
module.exports={register,types,hostPath};
