const crypto=require('crypto');
module.exports=function installWhatsAppSales(app,{pool}){
 const token=process.env.WHATSAPP_ACCESS_TOKEN;
 const phoneId=process.env.WHATSAPP_PHONE_NUMBER_ID;
 const verifyToken=process.env.WHATSAPP_VERIFY_TOKEN;
 const appSecret=process.env.WHATSAPP_APP_SECRET;
 const graph=process.env.WHATSAPP_GRAPH_VERSION||'v23.0';
 const base=process.env.APP_URL||'http://localhost:3000';
 function signatureOK(req){if(!appSecret)return true;const sig=String(req.headers['x-hub-signature-256']||'');if(!sig.startsWith('sha256='))return false;const raw=req.rawBody||Buffer.from(JSON.stringify(req.body||{}));const expected='sha256='+crypto.createHmac('sha256',appSecret).update(raw).digest('hex');try{return crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected))}catch{return false}}
 async function send(to,text){if(!token||!phoneId)throw Error('WhatsApp غير مضبوط');const r=await fetch(`https://graph.facebook.com/${graph}/${encodeURIComponent(phoneId)}/messages`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',recipient_type:'individual',to:String(to).replace(/\D/g,''),type:'text',text:{preview_url:true,body:String(text).slice(0,4000)}})});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j?.error?.message||`WhatsApp HTTP ${r.status}`);return j}
 async function salesChat(phone,message,name){let c=(await pool.query(`SELECT * FROM ai_sales_channels WHERE channel='whatsapp' AND external_user_id=$1`,[phone])).rows[0];let sid=c?.sales_session_id||null;const r=await fetch(`${base}/api/sales-agent/chat`,{method:'POST',headers:{'Content-Type':'application/json','X-Aqartkom-Channel-Secret':process.env.INTERNAL_CHANNEL_SECRET||''},body:JSON.stringify({message,session_id:sid,channel:'whatsapp',external_user_id:phone,external_name:name})});const j=await r.json();if(!r.ok)throw Error(j.error||'تعذر تشغيل موظف المبيعات');await pool.query(`INSERT INTO ai_sales_channels(channel,external_user_id,sales_session_id,display_name,last_inbound_at,updated_at) VALUES('whatsapp',$1,$2,$3,NOW(),NOW()) ON CONFLICT(channel,external_user_id) DO UPDATE SET sales_session_id=EXCLUDED.sales_session_id,display_name=COALESCE(EXCLUDED.display_name,ai_sales_channels.display_name),last_inbound_at=NOW(),updated_at=NOW()`,[phone,j.session_id,name||null]);return j}
 app.get('/api/channels/whatsapp/webhook',(req,res)=>{if(req.query['hub.mode']==='subscribe'&&verifyToken&&req.query['hub.verify_token']===verifyToken)return res.status(200).send(req.query['hub.challenge']);res.sendStatus(403)});
 app.post('/api/channels/whatsapp/webhook',async(req,res)=>{res.sendStatus(200);if(!signatureOK(req))return;try{for(const entry of req.body?.entry||[])for(const change of entry.changes||[])for(const m of change.value?.messages||[]){if(m.type!=='text')continue;const phone=String(m.from||'').replace(/\D/g,'');if(!phone)continue;const name=change.value?.contacts?.find(x=>x.wa_id===m.from)?.profile?.name||null;const duplicate=(await pool.query(`INSERT INTO ai_channel_events(channel,external_event_id,event_type,payload) VALUES('whatsapp',$1,'message',$2) ON CONFLICT(channel,external_event_id) DO NOTHING RETURNING id`,[m.id,JSON.stringify(m)])).rows[0];if(!duplicate)continue;const j=await salesChat(phone,m.text?.body||'',name);let reply=j.reply||'أخبرني بما تبحث عنه من عقار.';if(j.results?.length){reply+='\n\n'+j.results.slice(0,3).map((p,i)=>`${i+1}) ${p.title} — ${Number(p.price||0).toLocaleString('en-US')} ${p.currency||''}\n${base}/property.html?id=${p.id}`).join('\n\n')}await send(phone,reply);await pool.query(`UPDATE ai_sales_channels SET last_outbound_at=NOW(),updated_at=NOW() WHERE channel='whatsapp' AND external_user_id=$1`,[phone]);}}catch(e){console.error('WhatsApp sales webhook',e)}});
 app.get('/api/channels/whatsapp/status',async(_req,res)=>res.json({configured:Boolean(token&&phoneId&&verifyToken),webhook:`${base}/api/channels/whatsapp/webhook`,graph_version:graph}));
 return {send};
};
